### ISSUE TITLE
Service stopped When Changing DICOM File Compression

### ISSUE THREAD

**Issue by enasbond** [fo-dicom/fo-dicom#1796] opened 2024-05-26 12:49 UTC
Description:
When attempting to change the compression of the attached DICOM file, the application crashes, causing the service to terminate unexpectedly. This issue has occurred every time I used the attached file and generates an error in the attached Windows Event Viewer.

To Reproduce
public static DicomTransferSyntax[] GetSupported()
{
var nativetranscoder = new NativeTranscoderManager();
return DicomTransferSyntax.KnownEntries
.Where(t => nativetranscoder.CanTranscode(t, DicomTransferSyntax.ImplicitVRLittleEndian))
.ToArray();
}

var dicomFile = DicomFile.Open(inputFile);

string fileTs = dicomFile.Dataset.InternalTransferSyntax.UID.UID;

if (fileTs == transferSyntax)
{
return true;
}

var newFile = dicomFile.Clone(DicomTransferSyntax.Parse(transferSyntax));

newFile.Save(outputFile);

Unhandled exception.
FellowOakDicom.Imaging.Codec.DicomCodecException: Unable to determine bit depth: JPEG syntax error!

Screenshot
![image](https://github.com/fo-dicom/fo-dicom/assets/150520746/808262e2-5835-4d91-baf0-4cc12e78f004)
![image](https://github.com/fo-dicom/fo-dicom/assets/150520746/76d937f9-5781-4e30-9ccb-edd30ef9f306)
[image.zip](https://github.com/fo-dicom/fo-dicom/files/15447495/image.zip)

Environment:

OS:
fo-dicom nuget package version: 5.1.2
fo-dicom.Codecs nuget package version: 5.13

**Comment by mrbean-bremen** [comment] 2024-05-26 13:29
Does that happen with any file and any transfer syntax? From your code it is unclear which transfer syntax you are using. Also, the code is not syntactically correct - I guess that it is pseudo-code. It would help to have a real reproducible example.

_EDIT_: I had missed the attached DICOM file, sorry. Is this the file that has been created after transcoding? dcmdump says:
```
E: Found explicit length Pixel Data in top level dataset with transfer syntax JPEG Lossless, Non-hierarchical, 1st Order Prediction: Only undefined length permitted
E: dcmdump: Pixel data in top level dataset in compressed Transfer Syntax uses explicit length: reading file: image.dcm
```
So this indeed looks like the conversion has been wrong. If fixing the length to undefined, it is still invalid:
```
W: DcmItem: Length of element (7fe0,0010) is not a multiple of 2 (VR=OW)
W: DcmSequenceOfItems: Reached end of stream before the end of sequence PixelData (7fe0,0010)
E: dcmdump: Sequence Delimitation Item missing: reading file: image.dcm
```
Do you also have the original file before the transcoding?

Also: this is with the newest codecs, which has been released a few days ago. Does it also happen with the previous version?

**Comment by enasbond** [comment] 2024-05-28 08:39
Thank you so much for your feedback.

I have attached a sample test application using Windows Forms. Please try running the attached file.

I am aware that this file has issues, but my primary concern is preventing the application from terminating. In my production environment, which is a Windows Service, it is crucial that the service does not stop when such errors occur.


[TransCoderTest.zip](https://github.com/fo-dicom/fo-dicom/files/15466424/TransCoderTest.zip)
[image.zip](https://github.com/fo-dicom/fo-dicom/files/15466432/image.zip)

**Comment by mrbean-bremen** [comment] 2024-05-28 09:07
Thanks! The image you attached is the same (broken) image as above after transcoding (I guess). Do you also have the original image?

**Comment by enasbond** [comment] 2024-05-28 09:17
The attached image is the original image (before compression) that I currently have, which causes the application to crash when attempting compression. My primary concern is to prevent the service from stopping, even if the compression fails.

The image can be viewed with radiant
![image](https://github.com/fo-dicom/fo-dicom/assets/150520746/ca0207eb-6846-4d2a-bfd8-93dc6ccda93e)

**Comment by mrbean-bremen** [comment] 2024-05-28 09:27
Ah, so the original image is invalid (I can see that some viewers are able to display it regardless, while others can't), and the problem is that transcoding crashes with an invalid image - not what I understood at the beginning - I thought the transcoding itself caused invalid images.

I would guess that the crash happens in the codecs code (I can have a closer look tonight), which is outside of fo-dicom scope. In this case there wouldn't be much fo-dicom can do, I think...

**Comment by enasbond** [comment] 2024-05-28 09:38
Thank you for your update.

Initially, I created an issue for fo-dicom codecs, and they recommended that I send a new issue to you. 
https://github.com/Efferent-Health/fo-dicom.Codecs/issues/70

I'm not primarily interested in fixing the corruption issue right now. My main focus is to prevent the service from crashing. The crash is the higher priority for me to resolve.

**Comment by mrbean-bremen** [comment] 2024-05-28 09:46
Ah, I see now. You want to be able to ignore that `DicomCodecException` that is thrown in the fo-dicom code (or configure it so that it is not thown).

**Comment by enasbond** [comment] 2024-05-28 10:01
Yes, I have also added this code to my Windows service as well as in the test application I sent to you. However, the crash still occurs when I try to compress the attached file. I believe the access violation happens in the codecs.


  static void InitExceptionHandler()
  {
      // Global exception handling for unhandled exceptions in the current AppDomain
      AppDomain.CurrentDomain.UnhandledException += (sender, e) =>
      {
          HandleException(e.ExceptionObject as Exception);

      };


      // Global exception handling for unobserved task exceptions
      TaskScheduler.UnobservedTaskException += (sender, e) =>
      {
          HandleException(e.Exception);
          e.SetObserved();
      };
  }

**Comment by mrbean-bremen** [comment] 2024-05-28 10:22
> I believe the access violation happens in the codecs.

Yes, given that the callstack originates in Dicom.Native.Dll (which is part of the Codecs), this is very probable.

**Comment by mrbean-bremen** [comment] 2024-05-28 19:49
Hm, I cannot reproduce this. I have not ran your whole application, but the function `PerformTranscode` from your code with your file, and it failed as expected with an `IOException` (Not a JPEG file), which is caught and handled, _not_ in the codecs code. The context where this is called should not really matter, so something else must be different...
I tested in the current development branch, but there shouldn't be any related changes since the latest release, as far as I know.

**Comment by mrbean-bremen** [comment] 2024-05-29 04:46
Regardless, the problem exists in the Codecs part as [confirmed by @cbeltran1306](https://github.com/Efferent-Health/fo-dicom.Codecs/issues/70#issuecomment-2136154492) and will be fixed there, so I suppose we can probaly close this one.

**Comment by enasbond** [comment] 2024-05-29 09:00
Hello,

Thank you for the clarification. Since the issue has been confirmed to reside in the Codecs part and will be addressed there, I agree that we can close this one.

And this codecs one must be opened as they closed it
https://github.com/Efferent-Health/fo-dicom.Codecs/issues/70

Thanks again for your assistance.

**Comment by enasbond** [comment] 2024-05-29 09:01
Regardless, the problem exists in the Codecs part as https://github.com/Efferent-Health/fo-dicom.Codecs/issues/70#issuecomment-2136154492 and will be fixed there, so I suppose we can probably close this one.


https://github.com/Efferent-Health/fo-dicom.Codecs/issues/70

**Closed as completed** 2024-05-29 09:00 UTC
Labels: new
