### ISSUE TITLE
RenderImage(frameNo) out of range for single image DICOMs

### ISSUE THREAD

**Issue by jmiglietta-inc** [fo-dicom/fo-dicom#361] opened 2016-10-03 22:25 UTC
When attempting to extract images from a DICOM containing 1 image using code as below:
Dicom.DicomFile dicomfile = Dicom.DicomFile.Open(filePath);
Dicom.Imaging.DicomImage image = new Dicom.Imaging.DicomImage(dicomfile.Dataset);
for (int frameNo = 0; frameNo < image.NumberOfFrames; frameNo++)
{
    try
    {
        using (Bitmap bm = image.RenderImage(frameNo).As<Bitmap>())
        {
        }
}
 I receive the exception:
{"Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index"}

However, in QuickWatch, if I execute:
 image.RenderImage(-1).As<Bitmap>()

I'm able to get the Bitmap!

**Comment by anders9ustafsson** [comment] 2016-10-04 06:48
@jmiglietta-inc Which *fo-dicom* version are you using?

**Comment by jmiglietta-inc** [comment] 2016-10-20 18:12
fo-dicom version :2.0.2

**Comment by hdesouky** [comment] 2016-11-02 11:45
can you share this dcom  image file?

**Comment by anders9ustafsson** [comment] 2016-11-16 11:57
@jmiglietta-inc Please provide a more complete stack trace for the exception. Also, what happens if you try with the same image and *fo-dicom 3.0.0 beta*?

**Comment by anders9ustafsson** [comment] 2016-12-15 07:56
It is not obvious to me where this error should appear in the source code. Since we do not have a stack trace indicating the exact location of the error I will for the moment close the issue. If @jmiglietta-inc or anyone else can reproduce the error using version 3.0.0 beta 4, please feel free to re-open the issue.

**Closed by anders9ustafsson** 2016-12-15 07:56 UTC
Labels: evaluating
