### ISSUE TITLE
Saving DICOM file

### ISSUE THREAD

**Issue by icolovic** [fo-dicom/fo-dicom#800] opened 2019-02-19 05:43 UTC
### Expected behavior
After calling AddOrUpdate call to DicomFile,Save function should save any changes to a file.

### Actual behavior
Calling DicomFile.Save(fileName) produces exception:
System.IO.IOException: The process cannot access the file 'D:\DICOM.dcm' because it is being used by another process.

### Steps to reproduce the behavior
this._dicomFile = DicomFile.Open( this._fileName );
this._dicomDataSet = this._dicomFile.Dataset;
this._dicomFile.Save( fileName );

There is a file created on the disk but it is incomplete.  

Everything is working is I call Clone function with transfer syntax. Calling empty version of clone produces the same error. But this is introducing additional data conversion that is not needed.

### fo-dicom version and OS/platform
fo-dicom v4.0.0.0 Windows/Desktop.

**Comment by mia-san** [comment] 2019-02-19 05:50
any chance you are overwriting original file?

**Comment by icolovic** [comment] 2019-02-19 06:28
Yes. I am overwriting the original file. But that is true in both cases. 
The only difference is that when I call Clone function with TransferSyntax I do not get that exception. If I call Clone function (without parameters) or just Save function I get this exeption. 
When I get the exception the result is partially saved file od disk. It is strange. It looks like fo-dicom is locking it self from writing ti the file. And calling Clone (if transfer syntax in lossy compression) is intoducing additional image degradation.
[DICOMAfterJustSave.zip](https://github.com/fo-dicom/fo-dicom/files/2878584/DICOMAfterJustSave.zip)

.

**Comment by mia-san** [comment] 2019-02-19 07:07
fo-dicom does NOT read whole content in the dicom file on DicomFile.Open.
it skips reading 'large' elements and read them on-demand.
this is suppsedly due to memory consumption and performance reason.

when you're saving onto original file, fo-dicom try to read such 'large' element from original file.
but you have already opened the file for writing, now you get what you're seeing.

on 4.0.1, DicomFile.Open will have option to 'read all the elements no matter how large it is'.
for time being, you have to save the file into another name and replace with original.
of course, you can build 'development' branch yourself.

**Comment by icolovic** [comment] 2019-02-19 17:33
Thank you for this information. Now I understand why using Clone function worked. fo-dicom loaded all elements and was able to save the file. I am now using a temporary file.

**Comment by gofal** [comment] 2019-02-25 23:28
yes, it is as designed. I will close this issue, if there are any other questions please reopen this issue.

**Closed by gofal** 2019-02-25 23:28 UTC
Labels: question
