### ISSUE TITLE
HTj2k compression support

### ISSUE THREAD

**Issue by enasbond** [fo-dicom/fo-dicom#1727] opened 2024-02-17 22:12 UTC
I've been exploring the capabilities of fo-dicom for medical imaging applications and have found it to be a robust tool. 
However, I noticed that it currently lacks support for HTJPEG2000 compression. Given the growing adoption of HTJPEG2000 in medical imaging due to its superior compression efficiency and image quality, I believe adding support for this format would greatly enhance the versatility and usability of fo-dicom.

Could you please consider adding support for HTJPEG2000 compression in future releases of fo-dicom? This would enable us to efficiently store and transmit medical images while maintaining high fidelity and reducing storage requirements. I'm eager to hear your thoughts on this feature request and would appreciate any updates on its potential implementation.

**Comment by mrbean-bremen** [comment] 2024-02-18 07:11
This is a duplicate of #1687. Note that while `fo-dicom` now supports this in principle (at least in the development branch), it relies on the codecs from Efferent Health (`fo-dicom.Codecs`), which does [not support it yet](https://github.com/Efferent-Health/fo-dicom.Codecs/issues/54).

**Comment by jaime-olivares** [comment] 2024-07-04 06:33
HTJ2K is now supported with fo-dicom 5.1.3 and fo-dicom.Codecs 5.14.0
You can close this issue

**Comment by mrbean-bremen** [comment] 2024-07-04 06:51
Closing as mentioned.

**Closed as completed** 2024-07-04 06:51 UTC
Labels: duplicate
