### ISSUE TITLE
fo-dicom.Desktop: Lossy JPEG 8 Bit Image cannot be decoded

### ISSUE THREAD

**Issue by a21862** [fo-dicom/fo-dicom#928] opened 2019-09-23 07:38 UTC
### Expected behavior
JPEG Baseline (Process 1) is expected  to be supported

### Actual behavior
however, exception happens： “Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported.”

### Steps to reproduce the behavior

img = new DicomImage(dcmfilePath);
var image = img.RenderImage(0);

### fo-dicom version and OS/platform
v4.0.3
Windows 10, Visual Studio 2015,

**Comment by gofal** [comment] 2019-09-23 08:16
have you compiled with AnyCpu? To have codec support you need to compile explicit as x86 or x64

**Comment by amoerie** [comment] 2019-09-24 14:48
Possible duplicate of #911

**Comment by a21862** [comment] 2019-09-25 08:41
@gofal 
Thanks. It works after I complie the code explicitly as x64 !!! Appreciate your help

**Comment by a21862** [comment] 2019-09-27 01:55
specifying x64 resolves this issue.

**Closed** 2019-09-27 01:55 UTC
