### ISSUE TITLE
Creating DICOMDIR file using FO-DICOM

### ISSUE THREAD

**Issue by PoojaG-dev** [fo-dicom/fo-dicom#1045] opened 2020-06-09 14:32 UTC
I am working on C# application. I facing below issues-
1. I am trying to add structured report to DicomDirectory object using AddFile API.
But the report is getting added as an image, is there any way to correct this?

2. If at all it is not possible how to do it by manually adding DicomTags information to DicomDirectory class object?

Can you show some example?

--
Thank you

**Comment by gofal** [comment] 2020-06-10 07:36
I assume you know this sample https://github.com/fo-dicom/fo-dicom-samples/tree/master/Desktop/DICOM%20Media ?

What do you mean, it was added as an image? The DicomDirectory is a dictionary, containing patientid and patientname, then studyuids and studydescription, then seriesuids and seriesdescription and finally instanceuid and instanceSopClassUids. There is no imagedata in DicomDirectory.

DicomDirectory adds the required DicomTags for you into the tree-structure. But of course you can add additional DicomTags. When you call `AddFile`, then this functions returns an `DicomDirectoryEntry`. This class has 4 properties:

    /// <summary>
    /// Class that holds the Record entries of an entry across the different levels 
    /// </summary>
    public class DicomDirectoryEntry
    {

        public DicomDirectoryRecord PatientRecord { get; set; }
        public DicomDirectoryRecord StudyRecord { get; set; }
        public DicomDirectoryRecord SeriesRecord { get; set; }
        public DicomDirectoryRecord InstanceRecord { get; set; }

    }

there you can add/update (or even remove, but you should not ;-) ) DicomTags on the various levels of the tree structure.

**Comment by gofal** [comment] 2020-06-13 05:28
Something like that should work:

      var dd = new DicomDirectory();
      var directoryEntry = dd.AddFile(datasetWithReport);
      // now directoryEntry has 4 properties that link to the 4 datasets in each hierachy. there you can change or add values
      if (directoryEntry.InstanceRecord.GetString(DicomTag.DirectoryRecordType) == "IMAGE")
      {
          directoryEntry.InstanceRecord.AddOrUpdate(DicomTag.DirectoryRecordType, "REPORT");
          // reports remore some more entries
          directoryEntry.InstanceRecord.AddOrUpdate(DicomTag.CompletionFlag, 1);
          directoryEntry.InstanceRecord.AddOrUpdate(DicomTag.VerificationFlag, 0);
          // ....
      }

I can confirm, that the RecordEntryTypes in DicomDirectory are not complete.
Here they are defined: http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_F.5.25.html
I can see the entry type F.5.25 "SR Document Directory Record Definition" where the DirectoryRecordType is "SR DOCUMENT". But I could not find a definition where the DirectionryRecordType would we "REPORT". Is there another source of definitions in DICOM standard? otherwise I would complete the list ad defined in F.5

**Comment by PoojaG-dev** [comment] 2020-06-18 04:52
Hi,
I was working on the snippet provided but did not get how to add directoryEntry to DicomDirectory object.
Also tried adding information related to patient, study, series.... using Dicomequence to dataset of DicomDirectory but then it was not added to RootDirectoryRecord.

I wonder, if the structured report is also a dicom file then why it doesn't get added to DICOMDIR file properly.

**Comment by PoojaG-dev** [comment] 2020-09-15 13:29
Hello,
I am still facing the same issue while adding report file to DICOMDIR file.
Is this issue resolved in the latest fo-dicom version i.e. 4.0.6.? 
May I expect the bug fix soon?
Or do you recommend me to go for some manual approach of creating dicomdir file?

**Comment by gofal** [comment] 2020-09-16 06:07
Hi,
no, sadly this bug is not fixed in 4.0.6.

The issue is here:
https://github.com/fo-dicom/fo-dicom/blob/d42e47a86ee0fcf150a707bdeb798a60419658f6/DICOM/Media/DicomDirectory.cs#L525
In the method `CreateImageRecord` that is called by `AddFile` and `AddNewRecord` there is always a new entry with type "Image". Here schould be some check depending on AbstractSyntax of the file to add.

Do you think you can take a look at this and try to fix in a pull request?
Otherwise I beg your patient and I will do that as soon as I can.

**Comment by PoojaG-dev** [comment] 2020-09-22 03:28
Hi,
Suppose I fix the issue and submit the code, how much time it will take to release it in the next version?
Based on your response I will have to manage the tasks at my end and convey the deadlines.

**Comment by gofal** [comment] 2020-09-22 05:48
Great, thanks!
There is no fixed release-date. But there is one roughly every quarter. The last release was 2 months ago, so I think I will go toward the next release. Therefore all bug-issues should be solved, then I will do the release.

**Closed** 2020-11-01 10:03 UTC
Labels: bug
