### ISSUE TITLE
Dicom store request fails with SC file (secondary capture) in 4.0.5 version but success in 4.0.4

### ISSUE THREAD

**Issue by VitMosin** [fo-dicom/fo-dicom#1129] opened 2020-10-16 14:52 UTC
### Expected behavior
Dicom store request is successfully completed

### Actual behavior
[13:43:47 INF] CUSTOMER  -> Association request:
Calling AE Title:       MYSCU
Called AE Title:        CUSTOMER 
Remote host:            test.keenetic.link
Remote port:            15432
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 4.0.5
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  2
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  Explicit VR Little Endian
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[13:43:47 INF] CUSTOMER <- Association accept:
Calling AE Title:       MYSCU
Called AE Title:        CUSTOMER 
Remote host:            test.keenetic.link
Remote port:            15432
Implementation Class:   Unknown [1.2.826.0.1.3680043.8.2198]
Implementation Version: Customer version
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  2
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  Explicit VR Little Endian
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[13:43:47 INF] CUSTOMER -> C-Store request [2]
[13:43:50 INF] CUSTOMER <- Abort: ServiceProvider - UnexpectedPDU
[13:43:50 INF] Queue(s) not empty, PDUs: 0, messages: 0, pending requests: 1
[13:43:50 WRN] [SENDING REQUESTS] Association is aborted while sending requests, cleaning up...
[13:43:50 INF] Socket error while reading PDU: OperationAborted [995]
[13:43:50 INF] Connection closed
[13:43:50 ERR] Association Abort [source: ServiceProvider; reason: UnexpectedPDU]

### Steps to reproduce the behavior
Send SC file

### fo-dicom version and OS/platform
fo-dicom 4.0.5 windows\linux both

**Comment by gofal** [comment] 2020-10-19 06:08
Sadly I cannot ready the reason for error from this logfile. What does the logfile of version 4.0.4 look like, when it worked fine?
And is this issue only with SC files? So CT, MR, CR, US and so on all other work fine?
4.0.5 is not the recent version. Could you please try to reproduce this issue with latest version 4.0.6?
Thanks.

**Comment by VitMosin** [comment] 2020-10-19 06:44
When it worked fine (f.ex. with SR file) it looks like..
`
[13:43:22 INF] CUSTOMER -> Association request:
Calling AE Title:       MYSCU
Called AE Title:        CUSTOMER
Remote host:            test.keenetic.link
Remote port:            15432
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 4.0.5
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Enhanced SR Storage
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[13:43:22 INF] CUSTOMER <- Association accept:
Calling AE Title:       MYSCU
Called AE Title:        CUSTOMER 
Remote host:            test.keenetic.link
Remote port:            15432
Implementation Class:   Unknown [1.2.826.0.1.3680043.8.2198]
Implementation Version: Customer version
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Enhanced SR Storage
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[13:43:22 INF] CUSTOMER -> C-Store request [1]
[13:43:22 INF] CUSTOMER <- C-Store response [1]: Success
[13:43:22 INF] CUSTOMER -> Association release request
[13:43:22 INF] CUSTOMER  <- Association release response
[13:43:22 INF] Connection closed
`
The other files seem to be sent normally (f.ex. MG or SR files)
I tried 4.0.6 version too and get error there.
But also I should to point that it happens with only one customer.

**Comment by gofal** [comment] 2020-10-19 10:12
ok, the handshakres looks pretty the same.
So then I only have one more explanation: the problem could be on server-side. Have you tried to send a SC file to the one server that fails with an other tool? Maybe you try the free commandline-tool dcmtk from Offis, or any other. Could be that the server has problems processing SC files (because of some missing modality-based configuration....).
Just guessing, because based on the information you gave so far I do not have an idea where in fo-dicom a bug could be.

**Comment by VitMosin** [comment] 2020-10-19 11:31
I tried to send with storescu project from fo-dicom-samples. And I got error. 
I'll try utility dcmtk and will write the result soon.
Thank you for the answer.

**Comment by mia-san** [comment] 2020-10-19 16:27
just curious, fo-dicom has 2 DicomClient now:
- Dicom.Network.DicomClient
- Dicom.Network.Client.DicomClient

both DicomClient fails?
//

**Comment by VitMosin** [comment] 2020-10-21 12:33
> just curious, fo-dicom has 2 DicomClient now:
> 
> * Dicom.Network.DicomClient
> * Dicom.Network.Client.DicomClient
> 
> both DicomClient fails?
> //

We use the second one Dicom.Network.Client.DicomClient

**Comment by mia-san** [comment] 2020-10-21 12:43
yes, I know Dicom.Network.DicomClient is marked as obsolete.
I thought there might be a chance that older client works, just for data point.
if it works, newer DicomClient is behaving differently than older one.
//

**Comment by gofal** [comment] 2020-10-21 13:52
here are the canges done in version 4.0.5: https://github.com/fo-dicom/fo-dicom/blob/development/ChangeLog.md#v405-5182020
I also went through the commits between realse 4.0.5 and 4.0.4. There was nothing changed in DicomClient that might explain this.

**Comment by VitMosin** [comment] 2020-12-10 21:05
I returned to this problem. And I was wrong about the version. Starting from version 4.0.6 the problem starts. 4.0.7 also with a problem. But 4.0.5 works without errors.
Let me remind you that any version of the client works with dcmtk. But there is a problem with the customer's server. And on separate files. From the release changes I can see that there were a lot of changes in 4.0.6.
Maybe it makes sense to attach an anonymized file?

**Comment by gofal** [comment] 2020-12-27 20:27
yes, having some sample data to reproduce an issue is always a good idea, if it is possible.

**Comment by gofal** [comment] 2024-03-25 11:14
Closing the issue due to inactivity.
If with the latest version of fo-dicom this issue still occurs, then please reopen this issue and provide actual informations.

**Closed by gofal** 2024-03-25 11:14 UTC
