### ISSUE TITLE
Fo-dicom test on agfa equipment generating three prints in the job queue

### ISSUE THREAD

**Issue by megarockss** [fo-dicom/fo-dicom#1363] opened 2022-03-28 13:21 UTC
Good morning, I'm a student and I'm interested in software in the medical area, I'm testing the fo-dicom libraries using the example provided by you (which I'm very grateful), and on an x-ray agfa equipment when doing the conversion and send to print, three jobs are being generated in the print queue. The tomography equipment is coming out normal, only one impression. Using simulation software like Athena and Weasis also leaves only one impression. In the software that the hospital currently uses, only one comes out. Do you have any idea how I could handle this situation, and where I would do it? Thanks in advance for your help. Sincerely, Leandro.
[log collected.txt](https://github.com/fo-dicom/fo-dicom/files/8363120/log.collected.txt)

**Comment by megarockss** [comment] 2022-04-27 13:54
can anyone help me with this case?

**Comment by gofal** [comment] 2022-06-25 21:14
This seems like a duplicate of #1294 , maybe you find some hints there. And if you find out some things, please share your results also there.

**Comment by gofal** [comment] 2024-03-31 20:59
closing this issue due to inactivity. If you still have this issue with latest version of fo-dicom, please reopen this issue and provide actual information.

**Closed as completed by gofal** 2024-03-31 20:59 UTC
Labels: question
