### ISSUE TITLE
DICOM File load error

### ISSUE THREAD

**Issue by EdwardMarcus** [fo-dicom/fo-dicom#791] opened 2019-01-29 16:31 UTC
### Expected behavior
 DicomFile.Open(newfile.FullName, DicomEncoding.Default, StopDataSetReadMethod)

### Actual behavior  

  Dicom.DicomFileException: 'Input string was not in a correct format.' (see attached image)

### Steps to reproduce the behavior
 Loading a file

### fo-dicom version and OS/platform
Desktop 3.02        Win 10
![dicomfileload](https://user-images.githubusercontent.com/468788/51923616-55fbd480-23b9-11e9-9986-94cb7c8c60b6.jpg)

**Comment by mia-san** [comment] 2019-01-29 16:35
does same happens on 4.0.0?
what if you change the file name or path to the dicom file?

**Comment by EdwardMarcus** [comment] 2019-01-29 16:38
Yes I first tried 4.0 and reverted to 3.02 to see if the error repeated- it did.

**Comment by mia-san** [comment] 2019-01-29 16:47
ok, could you share the file in question?

**Comment by EdwardMarcus** [comment] 2019-01-29 16:50
I have to see it is clinical data.

**Comment by mia-san** [comment] 2019-01-29 16:58
just a guess, some element's value may not comply to VR's constraints.

**Comment by EdwardMarcus** [comment] 2019-01-29 17:01
That is my guess too –as the ts is explicit vr, and maybe the toolkit needs a handler.

**Comment by mia-san** [comment] 2019-01-29 17:04
do you have dcmtk available?
if so, what does dcmdump or dcm2xml say about the file in question?

**Comment by gofal** [comment] 2019-01-29 17:24
Can you see from stacktrace or somewhere else, which DicomTag is the one with the invalid string? and maybe you can see the string itself?
fo-dicom tries to be as tollerant as possible when reading from file or stream and only should be strict when creating new datasets.

**Comment by EdwardMarcus** [comment] 2019-01-29 17:35
Thanks for the suggestion

LeadTools opens it

**Comment by EdwardMarcus** [comment] 2019-01-29 17:38
Thanks  Here are the details

[cid:image001.png@01D4B7CF.8EF37460]

**Comment by mia-san** [comment] 2019-01-29 17:43
seems like the image is stripped of or something...

**Comment by EdwardMarcus** [comment] 2019-01-29 17:58
Thanks I will take a look.

The image is the output of a SHOWcase PHI tag cleanser.

**Comment by gofal** [comment] 2019-04-12 08:05
To continue investigating on this issue, we still need some more information about this file. Yould you upload an anonymized file to reproduce?

**Comment by heselhong** [comment] 2019-04-12 08:29
I also received this error message.
This message appears when VR is DS and the length is incorrect.

**Comment by gofal** [comment] 2019-08-26 19:53
Will close the issue now, since the problem seems to be fixed since 4.0.1 regarding to heselhong. Feel free to reopen this issue if there i still something left to do.

**Closed** 2020-02-27 19:35 UTC
