### ISSUE TITLE
RenderImage is error  for some special dicom files 

### ISSUE THREAD

**Issue by dhanzhang** [fo-dicom/fo-dicom#340] opened 2016-08-12 08:01 UTC
@anders9ustafsson    
Hi, when invoke  Dicom.Imaging.DicomImage.RenderImage  method  for  some   special dicom files is wrong!  just like  http://www.barre.nom.fr/medical/samples/files/MR-MONO2-12-angio-an1.gz    
the result files is like  
![mr-mono2-12-angio-an1 f](https://cloud.githubusercontent.com/assets/457633/17616227/01042906-60a6-11e6-943f-a8aea333b5bd.jpg)

**Comment by dhanzhang** [comment] 2016-08-12 08:04
@anders9ustafsson   when use   MicroDicom export  !  the  jpg file like that !
![111mr-mono2-12-angio-an1_1](https://cloud.githubusercontent.com/assets/457633/17616316/80c41d86-60a6-11e6-8b20-8d4482a4dd3d.jpg)

**Comment by dhanzhang** [comment] 2016-08-12 08:06
![111mr-mono2-12-angio-an1_1](https://cloud.githubusercontent.com/assets/457633/17616326/8d91059c-60a6-11e6-84ae-1e3dc152b13b.jpg)  
this JPG is  exported by MicroDicom!

**Comment by anders9ustafsson** [comment] 2016-08-12 08:23
@dhanzhang The DICOM file is missing the *Photometric Interpretation* (0028,0004) tag. Which version of *fo-dicom* are you using, and what platform are you running on?

**Comment by dhanzhang** [comment] 2016-08-12 09:03
@anders9ustafsson   when use  fo-dicom 2.0.2  is also  !  it's run with   vs2012 and windows 10  !

**Comment by anders9ustafsson** [comment] 2016-08-16 07:22
@dhanzhang When I try to display this image with *fo-dicom*'s DICOM Dump, version 2.0.2, I get an error message stating "Object reference not set to an instance of an object.", probably for the same (0028,0004) tag as was reported with 3.0.0-beta4.

Could you please provide a code snipped showing exactly how you came up with the image in your first comment above?

**Comment by dhanzhang** [comment] 2016-08-19 09:11
@anders9ustafsson    the code is 
`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace fodcmTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var dcmPath = @"MR-MONO2-12-angio-an1.dcm";

            var ax = Dicom.DicomFile.Open(dcmPath);
            if (ax.Dataset.Contains(Dicom.DicomTag.PhotometricInterpretation) == false)
            {
                ax.Dataset.Add(Dicom.DicomTag.PhotometricInterpretation, Dicom.Imaging.PhotometricInterpretation.Monochrome2.Value);
            }
            var img = new Dicom.Imaging.DicomImage(new Dicom.DicomDataset(ax.Dataset.OrderBy(x => x.Tag).ToList()));
           // var img = new Dicom.Imaging.DicomImage( ax.Dataset);
            var bmp=img.RenderImage().As<System.Drawing.Bitmap>();
            bmp.Save("CJ.BMP", System.Drawing.Imaging.ImageFormat.Bmp);
            bmp.Dispose();
        }
    }
}
`
and  fo-dicom  library is  download from  nuget with  
install-package  fo-dicom
![fdicom](https://cloud.githubusercontent.com/assets/457633/17804994/e213b68a-662f-11e6-94a0-a6e9f30b1cf0.png)

**Comment by dhanzhang** [comment] 2016-08-19 09:27
@anders9ustafsson the BMP file  referencered  in  first comment  !  by the way , 
in  PrecalculatedLUT.cs     I think the right shoud  be that:
   public int this[int value]
        {
            get
            { 
                    int p = value + _offset;
                    if (p < 0)
                    {
                        return _table[0];
                    }
                    if (p >= _table.Length)
                    {
                        return _table[_table.Length - 1]; 
                    }
                    return _table[p];
               
            }
        }

![a2](https://cloud.githubusercontent.com/assets/457633/17805363/d2a1d5ae-6631-11e6-8b27-a6f678eddae0.png)

**Comment by dhanzhang** [comment] 2016-08-19 09:30
@anders9ustafsson  when use  monochrome1  
![a3](https://cloud.githubusercontent.com/assets/457633/17805553/9c7044a6-6632-11e6-9611-35e7437ea59b.png)

**Comment by anders9ustafsson** [comment] 2016-09-09 13:05
@dhanzhang Which *fo-dicom* version are you using? The issue in *PrecalculatedLUT.c* that you point out was reported in #219 and fixed in #221. The fix should be included in version 2.0.2, at least.

**Comment by anders9ustafsson** [comment] 2016-09-09 15:25
@dhanzhang I have now looked overridden the photometric interpretation and looked more closely on the image. I notice that *Bits Stored* is set to 12, and I have the suspicion that this is what might cause the failure to display the image correctly. I will continue investigation when time permits. Thanks for reporting!

**Comment by anders9ustafsson** [comment] 2016-09-14 10:31
@dhanzhang Can confirm that the issue is due to insufficient handling of *Bits Allocated* that are not multiples of 8. Fix is underway.

**Closed** 2016-09-14 12:57 UTC
Labels: bug, in progress
