### ISSUE TITLE
Cannot run Dicom.Core.net on Windows

### ISSUE THREAD

**Issue by bibble235** [fo-dicom/fo-dicom#811] opened 2019-03-15 01:32 UTC
### Expected behavior
Program runs

### Actual behavior
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Dicom.DicomEncoding' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Dicom.IO.IOManager.get_BaseEncoding()
   at Dicom.DicomEncoding..cctor()
   --- End of inner exception stack trace ---
   at Dicom.DicomFile.Open(String fileName, FileReadOption readOption)
   at IainLib.IainClass.returnAString()
   at IainApp.Program.Main(String[] args) in C:\Users\Iain William Wiseman\source\repos\IainLib\IainApp\Program.cs:line 10

### Steps to reproduce the behavior

Build two projects, an app .NET 4.6.1 and a lib .NetStandard 2.0
In the app

```
using System;
using IainLib;

namespace IainApp
{
    class Program
    {
        static void Main(string[] args)
        {
            string myString = IainClass.returnAString();
            Console.WriteLine(myString);
        }
    }
}

```
In the lib

```
using Dicom;

namespace IainLib
{
    public class IainClass
    {
        public static string returnAString()
        {
            var myFile = DicomFile.Open(@"E:\Images\NonPHI\GoodStudy\anon.dcm");
            return "blairrrrrrr";
        }
    }
}

```
Run it

### fo-dicom version and OS/platform
4.0.0, 4.0.1

**Comment by mia-san** [comment] 2019-03-15 02:30
hmm, I could not reproduce the problem with your code.

what package installed precisely?

in my case, for class library
  - fo-dicom 4.0.1
  - fo-dicom.NetCore 4.0.1
  - .Net Standard Library 2.0.3

and for application
  - fo-dicom 4.0.1
  - fo-dicom.Desktop 4.0.1

also, do you have following assemblies in your executable directory?
  - System.Text.Encoding.dll
  - System.Text.Encoding.Extensions.dll

**Comment by bibble235** [comment] 2019-03-15 06:07
This is because you have added desktop to the App which not required as the app content does not use dicom. This works on linux but not on windows. I would imagine people would want the same behaviour on both platforms

**Comment by mia-san** [comment] 2019-03-15 06:10
sorry to forgot to mention that I have tested above with Windows 10, VS2017.

**Comment by bibble235** [comment] 2019-03-15 06:11
Please remove the reference to Desktop.

**Comment by mia-san** [comment] 2019-03-15 06:26
OK, I removed the fo-dicom and fo-dicom.Desktop package from application.
now program doesn't run due to missing Dicom.Core.dll.

here's my test solution.
does this run on your environment?
[ConsoleApp1.zip](https://github.com/fo-dicom/fo-dicom/files/2969676/ConsoleApp1.zip)

**Comment by bibble235** [comment] 2019-03-15 06:57
So running

msbuild /p:Outdir=E:\binMe /p:Configuration=Release /p:Platform=X64

Gives 

![image](https://user-images.githubusercontent.com/745357/54414020-9c847300-475c-11e9-8b69-97aa37985c35.png)

**Comment by mia-san** [comment] 2019-03-15 07:02
yes, that's what happens without fo-dicom.Desktop package.
if you add fo-dicom.Desktop package to application, it should run fine, right?

**Comment by gofal** [comment] 2019-03-15 07:11
please take a look at #694 . Is this related?

**Comment by bibble235** [comment] 2019-03-16 04:06
Guess it could be the same as #694. I wondering if it is a phonological difference to how .netstandard libraries should work. This is clearly reproducable on 4.0.0 and 4.0.1. Yes you add the desktop package to the app for windows and it will work because the Dicom.Core.dll is overwritten by the one it the .Desktop package.

**Comment by mia-san** [comment] 2019-03-20 13:40
just for the record, what I've found so far.

- without fo-dicom.Desktop package
the application won't run due to missing Dicom.Core.dll, as we already see.
but class library itself and .net standard 2.0 assemblies are copied into application's bin directory.
I don't know if 'this is by design'(tm) or packaging.

- install fo-dicom package into application, without specifying platform.
nuget package manager *automatically* installs fo-dicom.Desktop package, which fixes missing Dicom.Core.Dll issue, as we already see as well.
visual studio(nuget package manager?) might be considering the application is '.net framework 4.6.1 application with .net standard 2.0 assemblies', *NOT* '.net standard 2.0 application'.

so #694 seems to be slightly different to me.
probably, having visual studio(nuget package manager) to do the job might be solution for now?

**Comment by bibble235** [comment] 2019-03-20 20:37
I know how to make it work. You added the desktop package to your app which replaces the dicom.core.net.dll from the fo-dicom package with the one from desktop as it is built last.

My issue is that we should not need the desktop package unless we use dicom in the app rather than the library

**Comment by mia-san** [comment] 2019-03-21 04:44
more info.

.NET Standard Library package has dependency declared to .net framework 4.6.1.
https://www.nuget.org/packages/NETStandard.Library/

fo-dicom.NetCore package has no specific dependency to platform.
https://www.nuget.org/packages/fo-dicom.NetCore/

probably build process thinks no runtime dependency to .net framework.
maybe dependency must be declared in fo-dicom.NetCore package.

**Comment by buckstephenh** [comment] 2019-03-21 11:14
Net standard project should not depend on .net framework since it should work on all platforms incl mobile.  Netcore project seems correct and can only depend on .aspnet core and not .net framework since it has to run on Linux and MacOS.  If you need native dlls by platform, I think we either issue platform specific build or copy libs in afterward.  But I think we just use the nuget dependency for fo-dicom and not the source so maybe that’s the difference.

**Comment by gofal** [comment] 2020-02-27 18:43
To solve this, you have to call

        Dicom.IO.IOManager.SetImplementation(new DesktopIOManager());

(see #941).

fo-dicom is moving towards pure netstandard, thus will be solved there.

**Closed by gofal** 2020-02-27 18:43 UTC
