### ISSUE TITLE
Problem in DicomFile.Save after invoke clone to compress

### ISSUE THREAD

**Issue by pancetiki** [fo-dicom/fo-dicom#1286] opened 2021-12-10 13:36 UTC
Hi, a have a problem now that I moved my program to .Net6.0 and Fo-Dicom 5. I make this simple code like an example of compressing and saving a DICOM object:

using FellowOakDicom;
using FellowOakDicom.Imaging.Codec;

new FellowOakDicom.DicomSetupBuilder().RegisterServices(
               s =>  s.AddFellowOakDicom()                                                                                                 
                    .AddImageManager<FellowOakDicom.Imaging.ImageSharpImageManager>()                   
                    .AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>()).SkipValidation().Build();

var lDF=DicomFile.Open(@"/Users/xxxx/Desktop/TestImg/1.2.392.200046.100.14.534885681240130665967560413271076274.dcm");
var lComp=lDF.Clone(DicomTransferSyntax.JPEG2000Lossless);
lComp.Save(@"1.2.392.200046.100.14.534885681240130665967560413271076274.dcmj2k");

### Expected behavior
I expect to store a J2K object, but instead of that I get an exception. 

### Actual behavior
Exception has occurred: CLR/System.NotImplementedException
An unhandled exception of type 'System.NotImplementedException' occurred in fo-dicom.core.dll: 'The method or operation is not implemented.'
   at FellowOakDicom.DicomDatasetWalker.DoWalk(IDicomDatasetWalker walker, Queue`1 items)
   at FellowOakDicom.DicomDatasetWalker.Walk(IDicomDatasetWalker walker)
   at FellowOakDicom.IO.Writer.DicomFileWriter.WalkDataset(IByteTarget target, DicomTransferSyntax syntax, DicomDataset dataset, DicomWriteOptions options)
   at FellowOakDicom.IO.Writer.DicomFileWriter.WriteDataset(IByteTarget target, DicomTransferSyntax syntax, DicomDataset dataset, DicomWriteOptions options)
   at FellowOakDicom.IO.Writer.DicomFileWriter.Write(IByteTarget target, DicomFileMetaInformation fileMetaInfo, DicomDataset dataset)
   at FellowOakDicom.DicomFile.Save(String fileName, DicomWriteOptions options)
   at Program.<Main>$(String[] args)

### Steps to reproduce the behavior
Try to compress like in my sample.

### fo-dicom version and OS/platform

  <ItemGroup>
    <PackageReference Include="fo-dicom" Version="5.0.1" />
    <PackageReference Include="fo-dicom.Codecs" Version="5.0.2" />
    <PackageReference Include="fo-dicom.Imaging.ImageSharp" Version="5.0.1" />
  </ItemGroup> 

I tried in MACOS and Windows, and I always get the same error. I'm under .Net6.0. 

I'm really exhaust of trying everything to make this run again, and I can't understant why the save method, found that use some method that are not implemented. Is that a bug? Will be nice if you can help me to understant where is my mistake and thank you for your great job.

Álex

**Comment by gofal** [comment] 2021-12-16 16:22
This bug was also reproducable in netframework 4.6.1. 
Some code, that worked perfectly with fo-dicom 5.0.0-alpha, now also throws this exception after updating to fo-dicom5.0.1

**Comment by mrbean-bremen** [comment] 2022-04-13 18:01
Just for the record: this works for me under current fo-dicom with .net 6 and .net core 3.1. It fails in .net framework 4.6.2 as it could not load `fo-dicom.Imaging.ImageSharp`. I haven't looked further, just wanted to know if this is still an issue.

**Comment by gofal** [comment] 2024-03-31 20:40
Also cannot reproduce it any more.
So closing this. But if you sill face the issue with latest versio nof fo-dicom, plese reopen this issue and provide actual informations.

**Closed by gofal** 2024-03-31 20:40 UTC
Labels: bug
