### ISSUE TITLE
DicomTranscoder.cs not found

### ISSUE THREAD

**Issue by brunodimauro** [fo-dicom/fo-dicom#176] opened 2016-01-05 19:59 UTC
Hello from Brazil!

I have just download the Release Candidate version which was released today from nuget and I'm getting the following error:

![dicomtranscoder](https://cloud.githubusercontent.com/assets/6087994/12125778/6425a6ec-b3d4-11e5-892a-387bf9b55518.jpg)

This error occurs at DicomImage instance, like when I do the following code:

```
string pathImportar = Path.Combine(path.FullName, filename);

//Saving the file in server folder
file.SaveAs(pathImportar);

DicomImage dicomImageImportar = new DicomImage(pathImportar);
```

When the application reaches this code line, it open the following browser:

![dicomtranscoderbrowser](https://cloud.githubusercontent.com/assets/6087994/12125916/57151cc0-b3d5-11e5-857a-f5327301eb17.png)

Note that the path is in Anders' ( I think it belongs to @anders9ustafsson )  path.

What am I doing wrong?

Thanks for the amazing open source code!

**Comment by IanYates** [comment] 2016-01-05 22:02
The browser is from visual studio's debugger.

You're hitting an exception.  Even without the source I still think you'll be able to get the call stack.  Can you let it continue to crash and then give us full exception with call stack (aka "stack trace"). 

Is your app a console app, winforms, WPF?

**Comment by Ed55** [comment] 2016-01-05 22:55
May you have not read "Branking changes" and you need to adjust your library initialization ...

BTW:
Apparently I have had an exception in this class as well trying to transcode an "DICOM3NoFileMetaInfo" type of input file into Lossless JPEG using the DICOM Dump example.
This type does not provide an "InputSyntax" and crashes in "if (!InputSyntax.IsEncapsulated && !OutputSyntax.IsEncapsulated)". But of course this "a strange one" and more related to the Dump example.

Ian, Anders and other, thanks for your work.

**Comment by HelderMPinhal** [comment] 2016-01-05 23:46
Just off the top of my head, have you set the Build > Platform Target option?
The codec lib won't be added unless you manually place them there or let VS add it according the Platform Target.
Please confirm that you have Dicom.Native.dll or Dicom.Native64.dll, according to your OS, on your bin folder.

**Comment by brunodimauro** [comment] 2016-01-06 11:42
This error only occurs when I try to open those DICOM file: http://bit.ly/1RhoKQZ and http://bit.ly/1mBwiRN

When I was using the version 1.1.0, I was getting the following error:

```
No codec registered for tranfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression
```

Now I updated to 2.0.0 RC. Here's my Stack Trace:

```
   em Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, T defaultValue) na D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom].hidden\DICOM\DicomDataset.cs:linha 111
   em Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n) na D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom].hidden\DICOM\DicomDataset.cs:linha 70
   em BIRD.Web.Controllers.EstudoController.<>c__DisplayClass42.<Importar>b__1f(<>f__AnonymousType2`2 <>h__TransparentIdentifier7) na d:\00-Projetos\BIRD\BIRD\trunk\BIRD.Web\Controllers\EstudoController.cs:linha 459
   em System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   em System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   em System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   em System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   em BIRD.Web.Controllers.EstudoController.Importar(FiltroEstudoViewModels model) na d:\00-Projetos\BIRD\BIRD\trunk\BIRD.Web\Controllers\EstudoController.cs:linha 456
```

And the message:

```
Unable to get a value type of System.String from DICOM item of type Dicom.DicomOtherWordFragment
```

@IanYates I'm using a web application. I know it's not an approved platform yet, but works well with DCMs without codecs. In this web application, I just upload an .dcm file and render in png image.

@HelderMPinhal Is that a way to load codecs using web application? I was using version 1.1.0 and loading Dicom.Native.dll / Dicom.Native64.dll externally, this was working at my local machine and not working at deployed server.


Thank you all for the help!

**Comment by HelderMPinhal** [comment] 2016-01-06 11:44
`No codec registered for tranfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression`
On version 1, this is a typical error of not having the codec libraries in the bin folder.
Could you please post the file list on your bin folder?

**Comment by brunodimauro** [comment] 2016-01-06 12:02
@HelderMPinhal I did this to get Dicom.Native.dll / Dicom.Native64.dll:

At DicomTranscoder.cs:

```
public class DicomTranscoder {
		#region Static
		private static Dictionary<DicomTransferSyntax,IDicomCodec> _codecs = new Dictionary<DicomTransferSyntax,IDicomCodec>();

		static DicomTranscoder() {
            var root = AppDomain.CurrentDomain.BaseDirectory;
            var dllPath = Path.Combine(root, "library");
            LoadCodecs(dllPath);
		}

		public static IDicomCodec GetCodec(DicomTransferSyntax syntax) {
			IDicomCodec codec = null;
			if (!_codecs.TryGetValue(syntax, out codec))
				throw new DicomCodecException("No codec registered for tranfer syntax: {0}", syntax);
			return codec;
		}

		public static void LoadCodecs(string path = null, string search = null) {
			if (path == null)
				path = Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().EscapedCodeBase).LocalPath);

		    if (search == null)
		        search = "Dicom.Native*.dll";

			var log = LogManager.Default.GetLogger("Dicom.Imaging.Codec");
		    log.Debug("Searching {path}\\{wildcard} for Dicom codecs", path, search);

		    var foundAnyCodecs = false;

            DirectoryCatalog catalog;
		    try {
		        catalog = new DirectoryCatalog(path, search);
		    }
		    catch (Exception ex) {
		        log.Error("Error encountered creating new DirectCatalog({path}, {search}) - {@exception}", path, search, ex);
		        throw;
		    }

			var container = new CompositionContainer(catalog);
			foreach (var lazy in container.GetExports<IDicomCodec>()) {
			    foundAnyCodecs = true;
				var codec = lazy.Value;
				log.Debug("Codec: {codecName}", codec.TransferSyntax.UID.Name);
				_codecs[codec.TransferSyntax] = codec;
			}

		    if (!foundAnyCodecs) {
		        log.Warn("No Dicom codecs were found after searching {path}\\{wildcard}", path, search);
		    }
		}
		#endregion

```

At my library path:

![dicom library](https://cloud.githubusercontent.com/assets/6087994/12142005/c7cb57dc-b45b-11e5-8beb-1089a7a0b971.JPG)


This works at local machine. It doesn't work at deployed machine.

When I try to put both Dicom.Native.dll at bin path:
![dependencies](https://cloud.githubusercontent.com/assets/6087994/12142035/03cd5f6e-b45c-11e5-907a-7943105c6ce4.JPG)
(in english: Could not load file or assembly 'Dicom.Native 64' or one of its dependencies. An attempt to load a program with an incorrect format was made.)

My bin path:

![bin path](https://cloud.githubusercontent.com/assets/6087994/12142065/534ebf6a-b45c-11e5-8c02-c0d0df1468e3.JPG)

I thought upgrading to version 2.0.0 would solve this problem.

**Comment by IanYates** [comment] 2016-01-06 22:34
You need the Visual C++ runtime installed on the deployed machine.  It'll be on your dev machine as Visual Studio installs it for you.

**Comment by brunodimauro** [comment] 2016-01-07 18:15
@IanYates I did this, but still at the same error. I installed vcredist_x64 (Visual C++) 2013, 2015 and I tried to install 2010 but it's gives to me the message: "A newer version of Microsoft Visual C++ 2010 Redistributable has been detected on the machine".

I'm still stuck when loading an image with this codec (JPEG Lossless, Non-Hierarchical, First-Order Prediction) at deployed machine.

**Comment by anders9ustafsson** [comment] 2016-01-08 08:03
@brunodimauro You should not bother to install VC++ 2010 redistributables, *fo-dicom* 1.1 and 2.0 require VC++ 2013 redistributables.

**Comment by brunodimauro** [comment] 2016-01-08 11:47
@anders9ustafsson thanks for this information.
At my server, it's installed Visual C++ 2013 Redistributable (x64) and (x86)

![visual c 2013](https://cloud.githubusercontent.com/assets/6087994/12197085/15f5841a-b5eb-11e5-94fc-b4fcc0d6c920.JPG)

I developed an form application with only LoadCodecs method (loading from an external path, called library). This is the source code: http://bit.ly/1RdkJga

When running this form application at local machine: 
![load codecs local machine](https://cloud.githubusercontent.com/assets/6087994/12197115/67a77624-b5eb-11e5-9503-9c63b468e1de.JPG)

When running this form application at my deployed machine (the one with Visual C++ 2013 x64 and x86):
![load codecs deployed machine](https://cloud.githubusercontent.com/assets/6087994/12197134/9b0b3852-b5eb-11e5-9ebd-1aa4cb69e647.JPG)

Is there any Microsoft package to install at deployed machine?
Did someone try to import those DCM I sent?

I'm still trying to make this works.
Thanks for the help so far, folks!

**Comment by anders9ustafsson** [comment] 2016-01-08 12:02
@brunodimauro I have successfully loaded and displayed the DICOM you uploaded.

I know that @IanYates in his web applications loads the native codecs from an explicit location, using 

    TranscoderManager.LoadCodecs("directory_where_native_codec_dlls_are_located");

Have you tried the same?

**Comment by brunodimauro** [comment] 2016-01-08 12:21
@anders9ustafsson like this?

```
var root = AppDomain.CurrentDomain.BaseDirectory;
var dllPath = Path.Combine(root, "library");
DicomTranscoder.LoadCodecs(dllPath);
DicomImage dicomImageImportar = new DicomImage(pathImportar);
```

Where dllPath = "H:\BIRD\BIRD.Web\library"

![library path](https://cloud.githubusercontent.com/assets/6087994/12197719/a09e0966-b5f0-11e5-8879-1c257c96b36b.JPG)

At DicomTranscoder.cs

![get export](https://cloud.githubusercontent.com/assets/6087994/12197784/4a7a1010-b5f1-11e5-91ac-0009f3cc7bb8.JPG)

```
Error message: Dicom.Imaging.Codec.DicomCodecException: No codec registered for tranfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression
em Dicom.Imaging.Codec.DicomTranscoder.GetCodec(DicomTransferSyntax syntax) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\Codec\\DicomTranscoder.cs:linha 25
em Dicom.Imaging.Codec.DicomTranscoder.get_InputCodec() na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\Codec\\DicomTranscoder.cs:linha 83
em Dicom.Imaging.Codec.DicomTranscoder.DecodeFrame(DicomDataset dataset, Int32 frame) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\Codec\\DicomTranscoder.cs:linha 183
em Dicom.Imaging.DicomImage.Load(DicomDataset dataset, Int32 frame) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\DicomImage.cs:linha 273
em Dicom.Imaging.DicomImage..ctor(String fileName, Int32 frame) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\DicomImage.cs:linha 55
em BIRD.Web.Controllers.EstudoController.Importar(FiltroEstudoViewModels model) na c:\\projetos\\BIRD\\BIRD\\trunk\\BIRD.Web\\Controllers\\EstudoController.cs:linha 236. 

Stack trace: em Dicom.Imaging.Codec.DicomTranscoder.GetCodec(DicomTransferSyntax syntax) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\Codec\\DicomTranscoder.cs:linha 25
em Dicom.Imaging.Codec.DicomTranscoder.get_InputCodec() na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\Codec\\DicomTranscoder.cs:linha 83
em Dicom.Imaging.Codec.DicomTranscoder.DecodeFrame(DicomDataset dataset, Int32 frame) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\Codec\\DicomTranscoder.cs:linha 183
em Dicom.Imaging.DicomImage.Load(DicomDataset dataset, Int32 frame) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\DicomImage.cs:linha 273
em Dicom.Imaging.DicomImage..ctor(String fileName, Int32 frame) na c:\\projetos\\BIRD\\BIRD\\trunk\\DICOM\\Imaging\\DicomImage.cs:linha 55
em BIRD.Web.Controllers.EstudoController.Importar(FiltroEstudoViewModels model) na c:\\projetos\\BIRD\\BIRD\\trunk\\BIRD.Web\\Controllers\\EstudoController.cs:linha 236
```

**Comment by IanYates** [comment] 2016-01-10 23:40
@anders9ustafsson is right - I load the codecs myself by manually specifying a path.  To make development and build server stuff work well for me I use the _bin_deployableAssemblies folder as described  at http://haacked.com/archive/2011/05/25/bin-deploying-asp-net-mvc-3.aspx/, https://thedevstop.wordpress.com/2012/03/01/_bin_deployableassemblies-and-msbuild/, http://midnightprogrammer.net/post/Bin-Deploy-ASPNET-MVC-3-Application-With-SQL-CE-40-Entity-Framework.  Note that it's not as as complicated anymore as those posts indicate - it's really just a folder and all recent MSBuild flavours can understand it.

So I have a _bin_deployableAssemblies folder, and within that, I have a DicomCodecs folder.

I then have this code my my DicomConfig.cs file (called by my global.asax.cs, or statup.cs if you're doing newer web dev)

```
            //Grab codecs
            var filter = "Dicom.Native*.dll";

            var binDeployableFolder = System.IO.Path.Combine(application.Server.MapPath("/"), "_bin_deployableAssemblies", "DicomCodec");
            var binFolder = System.IO.Path.Combine(application.Server.MapPath("/"), "bin", "DicomCodec");

            var loadFolder = System.IO.Directory.Exists(binDeployableFolder) ? binDeployableFolder : binFolder;



            if (Directory.Exists(loadFolder))
            {
                logger.InfoFormat("Loading DICOM codecs from path {path} filtered to {filter}", loadFolder, filter);
                logger.LogIfException(() => TranscoderManager.LoadCodecs(loadFolder, filter), "Loading DICOM codecs");
            }
            else
            {
                logger.WarnFormat("No DICOM codec folder found at path {path} - no codecs will be loaded", loadFolder);
            }

```

That handles me running locally, where my codecs won't be in my bin folder.  It also handles running after deployment.  It also gracefully handles the case where I've done something wrong and the folder just doesn't exist.

I don't keep them in the bin folder because I have a couple of processes on app startup that like to scan available assemblies and one of them didn't appreciate coming across something that couldn't be loaded (different bitness and/or missing C++ runtime).

**Comment by IanYates** [comment] 2016-01-10 23:44
Also, do you have logging hooked up?  What log output are you getting?  (I scanned through the rest of the thread and didn't see this mentioned - apologies if I overlooked it)

**Comment by brunodimauro** [comment] 2016-01-11 16:26
@IanYates I did just like you said. I try to load codecs from "_bin_deployableAssemblies" at Global.asax and at deployed machine, it returns me nothing at "container.GetExports<IDicomCodec>())" and codecs are not loading. This causes the following known error: No codec registered for tranfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression

At deployed machine is installed:

![ms framework](https://cloud.githubusercontent.com/assets/6087994/12239294/24fa8088-b86f-11e5-8cea-b3d1f800160e.JPG)

I have already installed Microsoft Visual C++ 2013 Redistributable (x64 and x86). Windows is up to date. Which other component/patch I need to install?

**Comment by anders9ustafsson** [comment] 2016-01-14 12:54
@brunodimauro I am thinking a little bit about the error you are mentioning in your comment [here](https://github.com/fo-dicom/fo-dicom/issues/176#issuecomment-169308473). 

* Your web application, for which platform target is it built; *x86*, *x64* or *Any CPU*? 
* You get an error message regarding the *Dicom.Native64.dll*; what happens if you remove this file altogether, and only keep *Dicom.Native.dll* in your *bin* directory?

**Comment by brunodimauro** [comment] 2016-01-14 14:23
@anders9ustafsson here's the answers:

* I was building my application with *Any CPU*, although I've tested with *x86* and *x64* too.
* If I leave *Dicom.Native.dll* and/or *Dicom.Native64.dll* at bin path, it gives me an dependecy error (*Could not load file or assembly 'Dicom.Native.DLL' or one of its dependencies. The specified module could not be found.*). About this, which dependencies are required for those dlls?

By the way, I enabled 32-bit applications at AppPool.

I was searching about MEF (Managed Extensibility Framework), which its used to get Dicom.Native's dll. I believe that for some reason the MEF does not work at deployed machine.

**Comment by anders9ustafsson** [comment] 2016-01-19 14:25
@brunodimauro From your last answer, I get the impression that the issue is with your server, right? Maybe try another computer without VS installed? I would like to close this issue, any objections?

**Comment by brunodimauro** [comment] 2016-01-19 14:29
@anders9ustafsson I tried to use another computer without VS installed. Unsuccessfully.

Which dependencies are required for Dicom.Native* dlls?

**Comment by anders9ustafsson** [comment] 2016-01-19 14:34
VS 2013 C++ redistributables should be enough, I think?

I will try and find a computer in my "machine park" that hasn't had VS installed to see if I also run into native codec problems. I'll keep you posted.

**Comment by brunodimauro** [comment] 2016-01-19 14:41
@anders9ustafsson thanks

**Comment by brunodimauro** [comment] 2016-01-27 11:25
@anders9ustafsson did you get a machine to test?

I can send you the access of one machine without VS installed, if you want.
I really need help.

**Comment by anders9ustafsson** [comment] 2016-01-27 13:19
@brunodimauro Sorry for the delay.

I have now tested on a virtual machine, *Windows Server 2012 R2 Datacenter*, to run the *DICOM Dump* application.

First, when I try to display a JPEG 2000 compressed image, I get an error message stating that there is no codec for the requested compression type.

However, after I have installed the *Visual C++ 2013 Redistributables* (I chose the *x64* variant) from [here](https://www.microsoft.com/en-us/download/details.aspx?id=40784) the image displayed just fine. I just had to restart the application, I did not need to restart the whole server.

This is about as much as I can do to help you here. If you have the possibility, try out your application on a fresh virtual machine with the VC++ 2013 redistributables installed.

**Comment by anders9ustafsson** [comment] 2016-01-27 13:42
@brunodimauro One more thing. If your application is still failing, please try something simpler like the *DICOM Dump* application that also I tried. Then you'll at least know if you should continue to search for the error in the server setup or in your application.

**Comment by anders9ustafsson** [comment] 2016-01-28 10:09
@brunodimauro For cleanliness in the issues list, I will close this issue now. If your problems remain, please feel free to continue the discussion e.g. in the chat forum [here](https://gitter.im/fo-dicom/fo-dicom).

**Closed by anders9ustafsson** 2016-01-28 10:09 UTC
Labels: question
