### ISSUE TITLE
[Nuget] Native binaries are not copied into output folder when fo-dicom package is referenced using Nuget

### ISSUE THREAD

**Issue by michaelp** [fo-dicom/fo-dicom#87] opened 2015-09-20 18:21 UTC
**Description**: 
Native binaries are not copied into output folder when fo-dicom package is referenced using Nuget. 

**Steps to reproduce**:
- Create a project and add fo-dicom using nuget
- Compile the project with  x64 or x86 platforms
- Expected output: native dependencies will be found in the out put folder
- Actual output: native dependencies are missing.  *they are added only as references during compilation phase*

**Version** 
1.1.0

**Comment by anders9ustafsson** [comment] 2015-09-20 19:36
@michaelp Many thanks for the report, and for the proposed fix. We need to review it a little further. To begin with, I wonder if you could make a clarification: when you mention that you 

> * Compile the project with x64 or x86 platforms

have you then explicitly set the *Platform target* to x64 or x86, or have you only selected *(Build) Platform* x64/x86? The copy procedure is expected to work if you should set the *Platform target*:

![untitled](https://cloud.githubusercontent.com/assets/6515030/9982514/9406ce16-5fdf-11e5-95b7-c92e510ad860.png)

**Comment by michaelp** [comment] 2015-09-20 19:42
This is a screen shot of my configuration. 
The fix is supposed to solve transitive dependencies of a project that uses fo-dicom via Nuget.

![image](https://cloud.githubusercontent.com/assets/3293/9982524/b89c0070-5fad-11e5-87b9-4cbf9db1c94f.png)

**Comment by michaelp** [comment] 2015-09-20 20:09
To double check that the issue is reproducible i made the following steps:
- i created a new solution with two projects A and ATESTS
Such that x64 is defined as a platform for each project and in addition this is the active solution platform.
- Project A has fo-dicom as a nuget dependency
- Project ATESTS has a project reference to A and no nuget dependencies
After build the solution and i found the following
![image](https://cloud.githubusercontent.com/assets/3293/9982646/228a6154-5fb1-11e5-8f8f-250a0b3a79eb.png)
**As you can see inside the tests project - dicom is respected as transitive dependency but dicom native is not**
- now I applied the patch and clean  & build the solution
![image](https://cloud.githubusercontent.com/assets/3293/9982671/bf298b20-5fb1-11e5-9f0f-09bb70201403.png)
- The result is : you can see native dependency in both projects nicely placed into the output folder
- **I hope it helps**

**Comment by anders9ustafsson** [comment] 2015-09-20 20:45
Thanks again, @michaelp . The thing is, just because you select *Platform* x64 or x86 does not automatically mean that the *Platform target* is set to the same value; more often than not, this value remains at *Any CPU*.

Prior to your fix #88, when you built the project for platform x86 or x64, did you check the build warning messages? Did you then see the message:

> fo-dicom native libraries require the target platform to be explicitly specified.
> Change 'YOURPROJECT' Platform Target Build Project Property from 'Any CPU' to either x86 or x64 to remove this message.

If you did, that is a sign that you hadn't set the *Platform target* as intended.

Granted, the current approach is still rather non-intuitive, and if your proposed fix provides a smoother build procedure without resulting in any unwanted side-effects, then it is definitely something we want to adopt. We will review PR #88 thoroughly and get back to you as soon as possible.

In the mean time, many thanks for helping out!

Regards,
Anders

**Comment by michaelp** [comment] 2015-09-20 20:59
Thanks @anders9ustafsson  for your feedback. I hope that if you follow my extended comment with two screenshots  you will understand exactly what the issue was and why is it solved. The last comment shows that you did not notice that the platform was chosen correctly, otherwise the folder structure would be different. Please take a look at the comment and try to follow the described steps to reproduce the issue. If you in doubt then i can zip the solution and send it to you. Thanks for your attention.

**Comment by IanYates** [comment] 2015-09-21 01:13
I've got a few other libraries I use that have the similar dependency on an x86 or an x64 version of a helper DLL.  Example: https://github.com/pvginkel/PdfiumViewer#using-the-library, a third-part library from Essential Objects (another PDF utility thing) and SQL Server CE (for use with some ELMAH logging).

Because I'm making an ASP.Net app I use the capabilities of  the _bin_deployableAssemblies folder (http://haacked.com/archive/2011/05/25/bin-deploying-asp-net-mvc-3.aspx/) to get referenced files appearing in a x64 or x86 subfolder of bin and load the codecs from there based on the bitness at runtime.

This approach seems to generate less support requests and allows for the flexibility to handle AnyCPU without much of a problem.

However, I haven't had to worry about my tests come to think of it and probably should.  The fix does seem appropriate in that regard but I haven't tried to reproduce it myself locally.

**Comment by anders9ustafsson** [comment] 2015-09-21 07:11
@michaelp OK, maybe I am missing something, I will look more closely into your proposal soon, hopefully during the day. What I was trying to say was that I have not had any problems with native DLL copying *when Platform Target is set to x86 or x64*. But if the patch you are providing accomplishes the same thing in a more fail-safe manner, that's terrific, and of course that is something we should add to the repository.

**Comment by anders9ustafsson** [comment] 2015-09-26 11:09
Merged #88. Many thanks for this contribution, @michaelp !

**Closed by anders9ustafsson** 2015-09-26 11:09 UTC
Labels: in progress
