### ISSUE TITLE
WorklistService memory leak(MEM_COMMIT 35.414GB)

### ISSUE THREAD

**Issue by Sharemee** [fo-dicom/fo-dicom#1594] opened 2023-05-22 13:40 UTC
**Describe the bug**
I used Windbg to analyze Dump file. However, due to limited ability, it is impossible to judge where the problem lies.
But I'm not sure if this "FellowOakDicom.Network.DicomServer`1+RunningDicomService" holds a reference.

**To Reproduce**
I use WorklistSCU call WorklistSCP 5 times, SCP return empty data or mock data, then use dotnet-dump to create dump file, then use Windbg to analyze. Use Windbg commd "!dumpheap -stat", and find "WorklistService" keyword, you can see it have 5 count.
May be this reproduce can't fully reflect the real situation, but it looks like "WorklistService" reference is growing, not release.

**Expected behavior**
![ExpectedScreenshots](https://github.com/fo-dicom/fo-dicom/assets/28800794/088b3f9e-519f-47bb-9f07-c48999b1b361)

**Screenshots or test DICOM files**
![Windbg](https://github.com/fo-dicom/fo-dicom/assets/28800794/50fdb29e-8e4b-4bb0-956e-6668b9a220e3)

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows Server 2016 Datacenter x64
RAM: 32GB
Platform: .NET 6

Please help me, thank you -:), and forgive me for my poor English.

**Comment by amoerie** [comment] 2023-05-26 12:53
Hi

Out of curiosity I already ran an application that spawns 5000 associations on a single server.
My memory immediately rose to about ~40MB and stayed there the entire ride.
My memory profile displayed the traditional jigsaw pattern, which is what I like to see:
![image](https://github.com/fo-dicom/fo-dicom/assets/2063584/52fb2b45-e8b4-4524-a67f-a8bc3034458d)
So no, it does not look like there is a memory leak inside the DicomService disposal in DicomServer.

But enough about my tests. Let's address a few concerns with yours:
Did you trigger a garbage collect before making the dump? It's not because a reference still exists in memory that it is being "retained", it might just not have been finalized & collected yet.

And if it is being retained, you will probably want to use a tool like dotMemory to see the retention path to fix your memory leak.

**Comment by Sharemee** [comment] 2023-05-30 07:39
Thanks for your answer.

1. Windbg shows "system uptime: 272 days".
2. I'm not trigger a garbage collect before making the dump.

I observed that the submitted memory suddenly increased by 4GB during the period from Sunday night to next Monday morning, and the submitted memory changed slightly at other times.
Therefore, I suspect that this is related to the special request of the client, but I still can't find out the specific reason, only "OutOfMemory" error in the log, no warring.

As you said, I am trying more monitoring tools to analyze the behavior of the program.
I will restarting the program once a week to alleviate the memory leak problem.

**Comment by Sharemee** [comment] 2023-05-30 07:53
I'm not call GC.Collect function in program.

**Comment by happy0123** [comment] 2023-06-06 06:33
> Hi
> 
> Out of curiosity I already ran an application that spawns 5000 associations on a single server. My memory immediately rose to about ~40MB and stayed there the entire ride. My memory profile displayed the traditional jigsaw pattern, which is what I like to see: ![image](https://user-images.githubusercontent.com/2063584/241224149-52fb2b45-e8b4-4524-a67f-a8bc3034458d.png) So no, it does not look like there is a memory leak inside the DicomService disposal in DicomServer.
> 
> But enough about my tests. Let's address a few concerns with yours: Did you trigger a garbage collect before making the dump? It's not because a reference still exists in memory that it is being "retained", it might just not have been finalized & collected yet.
> 
> And if it is being retained, you will probably want to use a tool like dotMemory to see the retention path to fix your memory leak.

From May to June, we restarted the server twice, and in the early hours of Saturday or Sunday, the virtual memory suddenly increased in size by 10GB. On weekdays, virtual memory only slowly increases by a few hundred kilobytes per day.

What an amazing program! To open the log file, we didn't find any exceptional logs, only a CT machine queries this server every two minites.

**Comment by amoerie** [comment] 2023-06-06 07:01
Well I will never deny that bugs can occur in fo-dicom, but if you are seeing such odd behavior and you want help from me or one of the other contributors, you should provide us with memory dumps, traces, logs, anything you can get your hands on when the problem occurred. 
Without these things, we can only peruse the code and reason about it in a theoretical fashion. Furthermore, even if we would find something and fix it, it would be impossible to know that it was the root cause of your problem, and that your use case will be fixed.

**Comment by Sharemee** [comment] 2023-06-09 01:17
Oh thank you, I have a big big DUMP file, but I don't know how to send it to you, there is still 55MB left after 7z limit compression.

**Comment by amoerie** [comment] 2023-06-15 05:58
I suppose something like WeTransfer, SendGB, ... should work?

**Comment by Sharemee** [comment] 2023-06-19 09:31
WeTransfer, I just signed up for an account, but it's look like need the other person's email address.
So can I send the dump file directly to your email address?

**Comment by amoerie** [comment] 2023-06-20 14:07
Hi Sharemee, you can still send me the dump file at redacted
But even without the dump file, I think I know what's going on.
I believe that the first WorklistService will still be connected, and the other connections may have dropped. 
If so, you are running into the same issue as described here: #1468

Even if you don't use the MaxClientsAllowed setting, the problem is that if an initial connection is never closed, any additional DicomService instances are never removed from the list of DicomServer._services (`List<RunningDicomService>`) and so these are never cleaned up.
In a nutshell, every additional association incurs a memory allocation cost that is never returned.

For every DicomService that is never cleaned up, there are probably some lingering byte buffers that are not garbage collected. 
This issue will be fixed in the next fo-dicom release (provided my pull request https://github.com/fo-dicom/fo-dicom/pull/1602 is accepted of course)

For now, if this is your root cause, I would recommend the following:
- If it happens, reboot your service
- Investigate why you have connections that never close

Finally, upgrading to the next fo-dicom version when this fix is released should solve your problem.

**Comment by amoerie** [comment] 2023-06-21 06:48
Theory confirmed:

![image](https://github.com/fo-dicom/fo-dicom/assets/2063584/03a181aa-bf27-4d9d-8096-eb6f943dce1d)

Your first service is still connected, the rest is not.
Will be fixed by https://github.com/fo-dicom/fo-dicom/pull/1602

**Comment by Sharemee** [comment] 2023-06-21 08:17
Thank you very much.

**Closed as completed** 2023-08-18 12:19 UTC
Labels: bug, new

**Comment by happy0123** [comment] 2023-11-22 02:40
Hi amoerie, this bug is also exists. 
We haven't had a memory leak in a long time, But it suddenly happened last Sunday, the virtual memory reached 41GB.

The version of fo-dicom was 5.1.1, and had been download at 2023-08-31.

**Comment by happy0123** [comment] 2023-11-22 02:45
> Theory confirmed:
> 
> ![image](https://user-images.githubusercontent.com/2063584/247457041-03a181aa-bf27-4d9d-8096-eb6f943dce1d.png)
> 
> Your first service is still connected, the rest is not. Will be fixed by #1602

Hi amoerie, this bug is still exists.
We haven't had a memory leak in a long time, But it suddenly happened last Sunday, the virtual memory reached 41GB.

The version of fo-dicom was 5.1.1, and had been downloaded at 2023-08-31.

**Comment by amoerie** [comment] 2023-11-22 06:29
> > Theory confirmed:
> > 
> > ![image](https://user-images.githubusercontent.com/2063584/247457041-03a181aa-bf27-4d9d-8096-eb6f943dce1d.png)
> > 
> > Your first service is still connected, the rest is not. Will be fixed by #1602
> 
> Hi amoerie, this bug is still exists.
> We haven't had a memory leak in a long time, But it suddenly happened last Sunday, the virtual memory reached 41GB.
> 
> The version of fo-dicom was 5.1.1, and had been downloaded at 2023-08-31.
> 

Hi, the fix for this has been merged but has not been released yet. Please be patient for the next version.
