### ISSUE TITLE
Apply 16-bit LUT on WritableBitmap returned from RenderImage

### ISSUE THREAD

**Issue by soothingmusic** [fo-dicom/fo-dicom#1489] opened 2022-12-13 18:00 UTC
I'm struggling to apply 16 bit LUT on a grayscale image rendered as WritableBitmap.

```
private int[] lookup = new int[65535+1];
//....fill the lookup table

var bitmap = _dicomImage.RenderImage().As<WriteableBitmap>();
int width = bitmap.PixelWidth;
int height = bitmap.PixelHeight;
int stride = bitmap.BackBufferStride;
int bytesPerPixel = (bitmap.Format.BitsPerPixel + 7) / 8;

byte* pImgData = (byte*)bitmap.BackBuffer;

for (int row = 0; row < height; row++)
{
    for (int col = 0; col < width; col++)
    {
        //... pixelNewValue = lookup[pixelOldValue]
    }
}
```

How do i apply this LUT correctly to a grayscale image?

**Comment by gofal** [comment] 2022-12-27 12:14
See here: https://github.com/fo-dicom/fo-dicom/discussions/1490#discussioncomment-4502371

**Comment by mrbean-bremen** [comment] 2022-12-27 13:13
Duplicate of #1490

**Closed as completed by mrbean-bremen** 2022-12-27 13:13 UTC
Labels: question
