### ISSUE TITLE
PN Cannot Exceed 64 characters in total length

### ISSUE THREAD

**Issue by ChrisNewell-Inari** [fo-dicom/fo-dicom#1723] opened 2024-02-09 19:36 UTC
**Describe the bug**
Setting the PatientName to a value that exceeds 64 characters throws the exception Dicom.DicomValidationException

**To Reproduce**

call _DicomDataset.AddOrUpdate(DicomTag.PatientName, <your_string>)_ where the length of a single component is 64 chars long, while the other components are of normal length.

**Expected behavior**
For PN VR types, each component can have a maximum total of 64 characters in length: https://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html#note_6.1-2-1

**Environment**
Fellow Oak DICOM version: (e.g. 4.0.6)
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2)

**Comment by mrbean-bremen** [comment] 2024-02-09 20:16
The standard says:
> 64 chars maximum per component group

and:
> This group of five components is referred to as a Person Name component group.

So the limit is per component group, not per component, and this is also what is checked: each of the (maximum 3) component groups cannot contain more than 64 characters.

**Comment by mrbean-bremen** [comment] 2024-02-10 07:13
Not a bug, closing.

**Closed as completed by mrbean-bremen** 2024-02-10 07:13 UTC
Labels: new
