### ISSUE TITLE
Blazor WebAssembly DICOM file parsing

### ISSUE THREAD

**Issue by AJohnson2ACR** [fo-dicom/fo-dicom#1218] opened 2021-09-21 16:06 UTC
**What is, according to you, missing from fo-dicom? Please describe.**
While the there are ways to get DICOM files to be opened and parsed on the client-side using Blazor WebAssembly, one has to use a workaround. 

I think once considered, one can easily come up with some ideas of the benefit of being able to extract and process DICOM data on the client without sending entire files back to a centralized server (extracting PHI for example).

For example, using a file picker to open a DICOM file and getting a StudyInstanceUID. The following code will throw an exception, because the IBrowserFile interface does not implement a Seek() method:

![image](https://user-images.githubusercontent.com/73139235/134203675-59512ca3-36eb-41ae-b5ae-7082d99a5e10.png)

Once the highlighted line of code is hit, the following exception is thrown:

![image](https://user-images.githubusercontent.com/73139235/134203791-7d038d80-1e93-4f9b-b363-faa36a4600f3.png)

**Describe the solution you'd like**
The ability to use the IBrowserFile type to just pass the Stream into the DicomFile.Open method, without going through any additional conversion steps.

**Describe possible alternatives or existing workarounds you've considered**
One workaround I have come up with is to first add the Stream to a byte array, then pass that into a MemoryStream as follows:

![image](https://user-images.githubusercontent.com/73139235/134206442-7ebbd260-16b3-48e5-82ee-278f838894e7.png)

**Comment by amoerie** [comment] 2021-10-13 11:36
Without the ability to seek/rewind in a stream, what do you propose Fellow Oak DICOM would do exactly?
Can the file be read sequentially, byte by byte?

**Comment by mrbean-bremen** [comment] 2021-10-13 18:23
We had a somewhat related problem in pydicom, where seeking back was not supported in some scenarios (but seeking forward was). This had been resolved by using buffers in the (few) places where seeking backward was needed (like in sequences IIRC) as proposed by the OP, but only for a some parts. If seeking forward is also not possible, we could simulate that by just reading the number of bytes needed, though as that maybe a performnce problem, use it only for the case where no `Seek` is available.
I'm not familiar enough with the code to know if that is possible or if it even would make sense, though.

**Comment by gofal** [comment] 2021-10-17 18:32
I already took a closer look. there is no need to seek in input stream. The issue is that the reader has to skip the first empty 128 bytes. The implementation calls Seek to go 128 bytes forward. It is an easy change that the implementation just reads 128 bytes and throws them away in case that seeking is not supported.

**Comment by gofal** [comment] 2021-10-17 19:39
Oh dear, I have to revoke my last comment. With a simple change reading from a non seekable stream worked fine, but the BlazorinptuFilestream also does not allow setting the position to the past or even setting the position at all (https://github.com/SteveSandersonMS/BlazorInputFile/blob/master/BlazorInputFile/FileListEntryStream.cs). Without allowing to set the position the whole parsing process would habe to be redesigned.
The current implementation of storing the positions within the stream as marks to rewind saves a lot of memory.
otherwise we would have to cache many parts of the stream in memorystreams. And finally it would consume the same amount of memory as if you would just copy the whole file into one MemoryStream and then do the parsing on this Memorystream.

**Comment by amoerie** [comment] 2021-10-18 07:19
Look for usages of `IByteSource.Mark()` and `IByteSource.Rewind()`

This mark & rewind system is used in various places to "optimistically" read a few bytes and try to interpret them. However, if this fails, we rewind and try again in a different way. For example, in an explicit VR DICOM file, we try to read the next 2 bytes and parse those to a VR. However, if that fails, we rewind and move forward trying again with an implicit VR strategy.

Like @gofal said, if you wanted to remove this Mark & Rewind pattern, you would need to keep change the implementation of Mark & Rewind to something that, instead of changing the position of the stream, keeps those already read bytes in memory somehow. Perhaps it could be done by providing a decorator implementation of IByteSource, which would keep every read byte after a "Mark" in memory so that when you "Rewind", it uses those cached bytes in the next "Read" calls. But then you can start asking yourself the question how much better this strategy is compared to just reading the entire file to a MemoryStream.

**Comment by mrbean-bremen** [comment] 2021-10-18 07:41
Thank you - that makes sense. 

> But then you can start asking yourself the question how much better this strategy is compared to just reading the entire file to a MemoryStream.

Well, it would certainly be more complicated, but it might still use less memory. It depends of course on the size of the data, and if the image data is already read - it may just not be worth it.

Anyway, I like the approach to default to reading the whole data stream if no seek is available, given that the alternative would make the code more complicated and wouldn't gain that much. This is probably the best way to go.

**Comment by mrbean-bremen** [comment] 2021-11-07 09:28
Just to avoid confusion: the mentioned `FileListEntryStream` is not used here (it is deprecated and the repo is archived), what is used here is a [BrowserFileStream](https://github.com/dotnet/aspnetcore/blob/main/src/Components/Web/src/Forms/InputFile/BrowserFileStream.cs). It has the same capabilities though, e.g. it cannot seek or set the position (it can get the length though, that not all streams can).

**Closed** 2021-11-22 08:26 UTC
Labels: enhancement
