### ISSUE TITLE
Method 'OnCFindRequestAsync' in type 'xxx' from assembly 

### ISSUE THREAD

**Issue by cocosip** [fo-dicom/fo-dicom#1107] opened 2020-09-11 09:10 UTC
**Describe the bug**
Method 'OnCFindRequestAsync' in type 'YunPACS.NetGate.FoDicom.NetGateDicomService' from assembly 'YunPACS.NetGate, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'OnCGetRequestAsync' in type 'YunPACS.NetGate.FoDicom.NetGateDicomService' from assembly 'YunPACS.NetGate, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'OnCMoveRequestAsync' in type 'YunPACS.NetGate.FoDicom.NetGateDicomService' from assembly 'YunPACS.NetGate, Version=0.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**To Reproduce**
When my dicomService inherit 'IDicomCFindProvider', 'IDicomCGetProvider', 'IDicomCMoveProvider', it will thow an exception when application setup. If  remove these interface, it works well.   After degrade to `5.0.0-alpha1` ,the exception will not occur.
 
**Environment**
OS: Windows10 , Linux CentOS7.x
Platform: .net core 3.1.x
Fo-Dicom version: 5.0.0-alpha2

**Comment by gofal** [comment] 2020-09-16 18:53
That's not a bug. fo-dicom version 5 is still in development, thats why it is still released in version "alpha". There are no known bugs, but there are still some refactorings and changes that may change the API.

So an change between version 5.0.0-alpha1 and 5.0.0-alpha2 was:

https://github.com/fo-dicom/fo-dicom/blob/d42e47a86ee0fcf150a707bdeb798a60419658f6/FO-DICOM.Core/Network/IDicomCFindProvider.cs#L12-L23

if you are compiling against netcore 2 or netframework, then the interface requires a `Task<IEnumberable<Task<..>>>`, which is a rather complex structure and some kind of workaround to get an real asynchronous enumerable.
Since netcore3 there is the new `IAsyncEnumberable<..>`, so if you are compiling against netcore 3 or higher, then your interface has to return `IAsyncEnumerable`. This is why the interface does not match any more after updating to 5.0.0-alpha2.

**Comment by gofal** [comment] 2020-09-16 18:55
Great that you are already using version 5.0.0. Feel free to give feedback and post here if you have ideas for a better API. Now it will be far more easy to change the API than after 5.0.0 is finally released.

**Comment by cocosip** [comment] 2020-09-18 14:20
Sorry, my expression is not clear.
The dicomService was defined in  netstandard2.0, but the host was .net core 3.1。 So the api still use `Task<IEnumerable<Task<DicomCFindResponse>>> OnCFindRequestAsync` .
Maybe this problem is caused by nuget packaging?

**Comment by amoerie** [comment] 2020-09-21 06:32
@gofal perhaps we could install this package for .NET Standard 2.0 : https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/

Then we can get rid of the #ifdef clauses, and prevent the scenario that @cocosip is encountering

**Comment by gofal** [comment] 2020-09-21 08:07
The great thing about netstandard is, to have one assembly for all platforms.
The issues startet, when we created selveral targetframeworks. Then the library can be bound to one targetframework output and the application itself can be bound to an other targetframework output.

Was this IAsyncEnumerable the only reason for starting multiple targetframeworks? if yes, then using microsoft.bcl.asyncinterfaces would solve this.

**Comment by amoerie** [comment] 2020-09-21 09:20
Yes I think this was the only reason. And if we can avoid multi targeting,
we should. (The use case was quite strong here. IAsyncEnumerable is a
massive upgrade and perfectly fits the use case)



Op ma 21 sep. 2020 10:08 schreef Reinhard Gruber <notifications@github.com>:

**Closed** 2020-09-22 20:31 UTC
Labels: enhancement
