### ISSUE TITLE
Image getting damaged while converting 1.2.840.10008.1.2.4.91 (JPEG 2000 Image Compression) 

### ISSUE THREAD

**Issue by yadavvirus** [fo-dicom/fo-dicom#1209] opened 2021-09-12 09:54 UTC
**Describe the bug**
When i try to change Transfer sysntax to 1.2.840.10008.1.2.4.91 (JPEG 2000 Image Compression) and save, image is getting damaged.
I have tries DICOM Dump too with latest project 4.0.8 last commit.

this problem seen in latest xray and CT machine DICOM Files, Only unable to change syntax JPEG 2000 1.2.840.10008.1.2.4.91,
other than this its ok. 

**Environment**
Fellow Oak DICOM version: (e.g. 4.0.8)
OS: (e.g. Windows 10 x64)
Platform: (e.g. .NET Framework 4.6.2)

I am attaching sample of my file please try to change  its transfer syntax.
[anny.zip](https://github.com/fo-dicom/fo-dicom/files/7149370/anny.zip)

**Comment by mrbean-bremen** [comment] 2021-09-12 17:08
Out of interest - how can you re-encode an image in fo-dicom with another transfer syntax? I wasn't aware of this functionality. Can you show what you did?

**Comment by yadavvirus** [comment] 2021-09-13 02:06
@gofal sir please take a look into this problem, since i am waiting for solution from very long time. Thank you sir

**Comment by gofal** [comment] 2021-09-13 06:49
Yes, I know about #1083. Sadly I am not able to fix issues in Codec myself. We just took the OpenJpeg library (some c++ for windows) and integrated it. It seemed to work fine and stable for many years. Issues came up when fo-dicom more and more was expected to run on linux or mac (with netcore and netstandard). There Efferent is doing a great job with codecs, they ported it to run on other systems and they also are able to fix some things there. Did you post the issue, that transcoding crashed, on their gitub page? https://github.com/efferent-Health/fo-dicom.Codecs/

**Comment by mrbean-bremen** [comment] 2021-09-19 18:41
For reference: The issue is now also filed against the [Efferent codecs](https://github.com/Efferent-Health/fo-dicom.Codecs/issues/15).

**Comment by jaime-olivares** [comment] 2022-01-31 02:47
This issue is solved in Efferent's codecs

**Comment by yadavvirus** [comment] 2022-02-02 05:05
> This issue is solved in Efferent's codecs

Sounds Great Sir,
but still image getting damage while changing its transfer sysntax to JPEG2000Lossy.
Images are in #1083 and #1029.

Here My Code is like
```cs
using FellowOakDicom;
using FellowOakDicom.Imaging.Codec;
using FellowOakDicom.Imaging.NativeCodec;
using FellowOakDicom.Native.Codec;

namespace testDemo
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            new DicomSetupBuilder()
               .RegisterServices(s => s.AddFellowOakDicom().AddTranscoderManager<NativeTranscoderManager>())
               .SkipValidation()
               .Build();

            var dcm = "anny.dcm";
            var data = DicomFile.Open(dcm);            
            var img = new DicomFile(data.Dataset).Clone(DicomTransferSyntax.JPEG2000Lossy);
            img.Save("out.dcm");
            MessageBox.Show("done..");
        }
    }
}
```
Library I am using 

![image](https://user-images.githubusercontent.com/7027914/152095620-016356d1-45db-46ef-b60c-4d738e46a69b.png)

please guide me if i am doing wrong.

![image](https://user-images.githubusercontent.com/7027914/152095832-f7e22da6-b39c-476e-a951-d063e319c9ba.png)

**Comment by yadavvirus** [comment] 2022-02-02 05:08
[anny.zip](https://github.com/fo-dicom/fo-dicom/files/7983730/anny.zip)

DICOM file attached here
I am trying to compress in DicomTransferSyntax.JPEG2000Lossy.
Please help me.
Thank you

**Comment by mrbean-bremen** [comment] 2022-02-04 19:13
Your image is a monochrome image with 16 bits stored. I'm not familiar with JPEG2000, but as far as I know, this kind of data cannot be converted to any JPEG transfer syntax. @gofal - correct me if I am wrong.
_EDIT:_ Well, I was obviously wrong. JPEG2000 support monochrome 16 bit images.

**Comment by mrbean-bremen** [comment] 2022-02-04 19:42
Actually I may be wrong. I made a few tests, and indeed the JPEG syntaxes (including JPEG2000 Lossless) seem not to support this, but JPEG2000 seems to support it. The conversion also crashes for me, so it still looks like a bug in the transcoder. 

@jaime-olivares - do you have any idea why this happens? Should this (MONOCHROME2, 16 bit) be supported for this case?
If I try to debug this, it crashes in `DicomJpeg2000Codec.cs` in line 981:
```cs
           if (Convert.ToBoolean(Opj_encode_Windows64(cinfo, cio, image, eparams.index)))
```
This line causes a runtime error (0xC000 0374), which points to a corrupted heap (matching the error message shown by the OP). As far as I understand, the actual problem seems to be in the called OpenJPEG code (`opj_jp2_encode`), not sure if the input parameters are wrong, or the code has a bug.

_EDIT_: Corrected to match the actual source (instead of the decompiled source)

**Comment by mrbean-bremen** [comment] 2022-02-05 09:39
@yadavvirus - I recommend to discuss this in fo-dicom.Codecs. I don't think there can be anything done in fo-dicom.

**Comment by yadavvirus** [comment] 2022-02-05 12:40
@mrbean-bremen @jaime-olivares 
Sir same image I have compressed using leadtools codec and attached here Please Find Attachment
[xray.zip](https://github.com/fo-dicom/fo-dicom/files/8008022/xray.zip)
.

**Comment by mrbean-bremen** [comment] 2022-02-05 14:38
@yadavvirus - ~I suggest you write a new issue in `fo-dicom.Codecs`, as this is not related to your previous issue. You can link it to this issue, or copy over the relevant part.~
I created an issue in `fo-dicom.Codecs`, will leave this one open for tracking.

**Comment by kundanashish** [comment] 2023-02-12 08:22
Hi @yadavvirus 
I am still stuck here too.
Pls advise if we get any solution for this?

**Comment by jaime-olivares** [comment] 2023-02-23 22:21
We are reviewing in the following days

**Comment by kundanashish** [comment] 2023-04-12 04:26
Hi @jaime-olivares 
Please let me know if you get anything on this.

Thanks

**Comment by gofal** [comment] 2024-03-25 09:23
Closing this issue, as the discussion should be on the fo-dicom.Codec repository.

**Closed by gofal** 2024-03-25 09:23 UTC
Labels: duplicate

**Comment by mrbean-bremen** [comment] 2024-05-23 15:38
Fixed now in fo-dicom.Codec.
