### ISSUE TITLE
Anonymizer Profiles not anonymizing dicom header 

### ISSUE THREAD

**Issue by suyashdb** [fo-dicom/fo-dicom#691] opened 2018-05-22 16:08 UTC
### Expected behavior
Dicom anonymizer should anonymize atleast few dicom header fields. 
var anony = new DicomAnonymizer(profile);

### Actual behavior

Dicom header is absolutely same before and after anonymizing 

### Steps to reproduce the behavior

```
var testfile = DicomFile.Open(@"C:/Users/user1/Desktop/origtest.dcm");
var anony = new DicomAnonymizer();
anony.AnonymizeInPlace(testfile);
```

### fo-dicom version and OS/platform

3.0.2 Windows 7

**Comment by gofal** [comment] 2018-05-22 17:07
There are unit tests to verify that the anonymizer works. On Github CI they work well:
https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Desktop/DicomAnonymizerTest.cs
Do these methods fail on your machine?

**Comment by gofal** [comment] 2018-05-22 21:39
some nuget-packages are missing?

You could just create a new console project and add a reference to fo-dicom and a nuget package xunit. Then you copy the class into your project. Then you could call all the methods from the void Main-Method.

**Comment by gofal** [comment] 2018-05-24 05:01
Copied from group.google.com/fo-dicom:

Interestingly as reini pointed, without security profile its anonymizes dicom file but with security profile(i tried all profiles starting from basic one), there is no chnage in header:

Works:


     var testfile = DicomFile.Open(@"C:/Users/VHASFCBHOGAS/Desktop/origtest.dcm");
     var anony = new DicomAnonymizer();
     var test = anony.Anonymize(testfile);
     test.Save(@"C:/Users/VHASFCBHOGAS/Desktop/test_basicProfile.dcm");

Doesn't work:

            var testfile = DicomFile.Open(@"C:/Users/VHASFCBHOGAS/Desktop/origtest.dcm");
            var profile = DicomAnonymizer.SecurityProfile.LoadProfile(null, DicomAnonymizer.SecurityProfileOptions.BasicProfile);
            var anony = new DicomAnonymizer(profile);
            var test = anony.Anonymize(testfile);
            test.Save(@"C:/Users/VHASFCBHOGAS/Desktop/test_basicProfile.dcm");

**Comment by gofal** [comment] 2018-11-01 10:41
cannot reproduce it. I add an unit test with the code snipped above.

**Comment by gofal** [comment] 2018-11-01 11:05
please, if anybody can provide me a example (dicom dataset and code) of a not working anonymizer

**Comment by gofal** [comment] 2019-01-04 21:19
I will close this now, since the unit test works fine.

If there i a example that is not working, please feel free to reopen the issue

**Closed by gofal** 2019-01-04 21:19 UTC
Labels: bug, evaluating
