### ISSUE TITLE
SendAsync never returns or throws. 

### ISSUE THREAD

**Issue by rotoyo** [fo-dicom/fo-dicom#1358] opened 2022-03-22 06:16 UTC
**Describe the bug**

I intentionally unplugged the LAN cable for testing while sending 100 Dicom files to PACS server.
I expected to occur Exception but SendAsync never returns or throws no matter how waiting. 

I tried calling token.cacel() but  Exceptions don't occur still.

Because SendAsync is Task, I can't call interrupt like as Thread.

How can I disconnect from PACS in this case?

**To Reproduce**

            _tokenSource = new CancellationTokenSource();
            var token = _tokenSource.Token;

            var scu = DicomClientFactory.Create(PacsHost, PacsPort, false, ModalityAETitle, PacsAETitle);

            foreach (string dcm in _DcmList)
            {
                var request = new DicomCStoreRequest(dcm);
                request.OnResponseReceived = OnRespReceived;
                request.OnTimeout = OnRespTimeout;
                await scu.AddRequestAsync(request);
            }

            try
            {
                await scu.SendAsync(token); //intentionally  unplugged Lan cable 
            }
            catch(Exception err)
            {
                  log.error(err.Message);
            }
            finally
            {
                _tokenSource.Dispose();
            }

**Expected behavior**

Exception 

**Environment**
Fellow Oak DICOM version:  fo-dicom.core 5.0.2.0
OS: Windows10
Platform: NET Framework 4.7.2)

**Comment by amoerie** [comment] 2022-03-22 12:03
Probably a duplicate of #1325 ?

**Closed as completed** 2022-04-19 09:31 UTC
Labels: duplicate
