### ISSUE TITLE
I want to rescale a dicome slace, i.e. 1024*1024 (columns * rows) rescale to 1000*1000 (columns * rows))

### ISSUE THREAD

**Issue by bocheta** [fo-dicom/fo-dicom#1481] opened 2022-12-01 08:53 UTC
### Discussed in https://github.com/fo-dicom/fo-dicom/discussions/1480

<div type='discussions-op-text'>

<sup>Originally posted by **bocheta** December  1, 2022</sup>
Hi friends, is there anyway to rescale a dicome slice with fo-dicom and c#?
I tried first to convert dicom file to jpeg and then resize it, finally write the resized image in an array of bytes, but it does not work.
Any Idea?. Thank you .</div>

**Comment by mrbean-bremen** [comment] 2022-12-01 09:43
Close as duplicate of #1480

**Closed as completed by mrbean-bremen** 2022-12-01 09:43 UTC
