### ISSUE TITLE
Program crash when GC clear disposed bitmap from DicomImage

### ISSUE THREAD

**Issue by zhangyuwu** [fo-dicom/fo-dicom#634] opened 2017-11-09 04:24 UTC
### Expected behavior
switch to button3 or button4 should be Ok.

### Actual behavior
Program crashed at
   at System.Drawing.Image.get_Width()
   at System.Drawing.Image.get_Size()
   at System.Windows.Forms.PictureBox.ImageRectangleFromSizeMode(PictureBoxSizeMode mode)
   at System.Windows.Forms.PictureBox.OnPaint(PaintEventArgs pe)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

It seems like disposing an unused bitmap from DicomImage.RenderImage().AsBitmap() will cause other bitmaps corrupted.

### Steps to reproduce the behavior
1) Create a winform app
2) Add two instance variables named dcm1, dcm2 with the type DicomImage
3) Add a PictureBox to the form
4) Add four buttons, each button loads an image to picture box
    Button1 loads a bitmap about 1.7Mb
    Button2 loads a bitmap about 1.6Mb
    Button3 loads image from dcm1.RenderImage().AsBitmap()
    Button4 loads image from dcm2.RenderImage().AsBitmap()

    Each button shows the image by calling ShowImage() as below:

        void ShowImage(Image image)
        {
            if (pictureBox1.Image != image) {
                var oldImage = pictureBox1.Image;
                pictureBox1.Image = image;
                if (oldImage != null) {
                    oldImage.Dispose();
                    GC.Collect();
                }
            }
        }

        private void button1_Click(object sender, EventArgs e)
        {
            var image = Image.FromFile(@"D:\Temp\1.bmp");
            ShowImage(image);
        }

        private void button2_Click(object sender, EventArgs e)
        {
            var image = Image.FromFile(@"D:\Temp\2.bmp");
            ShowImage(image);
        }

        private void button3_Click(object sender, EventArgs e)
        {
            var img = dcm1.RenderImage().AsBitmap();
            ShowImage(img);
        }

        private void button4_Click(object sender, EventArgs e)
        {
            var img = dcm2.RenderImage().AsBitmap();
            ShowImage(img);
        }

5) Click button1 and button2 times, Ok
6) Now switch to button3 or button4, Crashed

### fo-dicom version and OS/platform
fo-dicom version: 3.0.2.0
Windows 2016 Enterprise
Visual Studio 2017

**Comment by anders9ustafsson** [comment] 2017-11-09 18:51
@zhangyuwu Thanks for reporting! Have also noted this exception occasionally. Will investigate.

**Comment by gofal** [comment] 2018-01-20 23:01
Sounds similar as issue #651. Solved it by imediatelly calling ".Clone()" after ".AsBitmap". Maybe this hint helps when investigating.

**Comment by mia-san** [comment] 2018-02-13 13:25
more simpler,
```
Bitmap bitmap;
using (var iimage = new DicomImage("dicom.file").RenderImage()) {
  bitmap = iimage.AsBitmap()
}
var width = bitmap.Width
```
would immediately cause exception on accessing Width property, doesn't need to wait for getting GCed.

under WinForms environment,
1. `DicomImage.RenderImage` actually returns `Dicom.Imaging.WinFormsImage`
2. `Dicom.Imaging.WinFormsImage` inherits `ImageDisposableBase<Bitmap>`
3. `ImageDisposableBase<Bitmap>` implements `Dispose(bool)`
4. `ImageDisposableBase<Bitmap>.Dispose(bool)` disposes member variable `image`
5. `ImageDisposableBase<TImage>` inherits `ImageBase<TImage>`
6. `ImageBase<TImage>.As<T>` essentially returns member variable `image`
7. `ImageDisposableBase<TImage>` does NOT override `As<T>`

here, suppose we have
```
var iimage = new DicomImage("dicom.file").RenderImage()
var bitmap1 = iimage.AsBitmap()
var bitmap2 = iimage.AsBitmap()
```
iimage, bitmap1 and bitmap2 actually share same bitmap.
therefore, once any one of those objects disposed or GCed, 3 bitmaps (actually 1 bitmap) are now disposed.
now, accessing bitmap causes exception.

override `Dicom.Imaging.WinFormsImage.Image` something like
```
  return (Bitmap)((Bitmap)(object)image).Clone())
```
might help ( looks ugly, though )

otherwise, change member variable `image` to byte array and
```
  return Image.FromStream(
    New MemoryStream(
      this.image
    )
  )
```

what do you think?
//

**Comment by gofal** [comment] 2018-02-14 06:58
Yes, great. Thats the kind of solution we need! 
Are you using the released fo-dicom (3.0.2 or previous) or are you compiling the fo-dicom library from latest source code? Because I reproduced this bug in release 3.0.2. When I wanted to fix it and ran the application with the latest sources, I could not manage to reproduce it. Anders Gustafson did some refactoring. like https://github.com/fo-dicom/fo-dicom/commit/882aadf68a6a6205327f0f9eedd56409b7de8846 or https://github.com/fo-dicom/fo-dicom/commit/e3c7daa046a5301870213633fbbbbe2ba02f96a4 and some more. Not sure if this has been (accidentally) fixed?

**Comment by mia-san** [comment] 2018-02-14 10:32
hi.
I use fo-dicom 3.0.2 from NuGet.
your "latest source" means development branch ?
both development branch and 3.0.2 seem to be doing same thing, i.e. return same bitmap with type-cast, as far as I see.
//

**Comment by gofal** [comment] 2018-02-15 06:40
ok, so this issue is still alive. 

I liked the idea that you showed in the example above: if you instanciate on DicomImage and call RenderImage() then every call to .AsBitmap returns the same image. Wouldn't that save a lot of memory? 
You are very deep in the code now and know it very well: would you see a downside if WinformsImage would not dispose the member variable image? but let the GarbageCollector dispose it if there is no other Bitmap referencing this image?

Otherwise I would prefer the Clone method. Since if you return a Bitmap with a memoryStream then the MemoryStream has to be open all the time. This would then not solve the disposing problem if the WinformsImage disposes the byte arrays or the MemoryStream.

Will you create a pull-request? this issue is marked for the 4.0 release. Would be great if there was a solution soon.

**Comment by mia-san** [comment] 2018-02-15 15:56
I've just done following steps to reproduce problem.

1.  download fo-dicom-development.zip from github fo-dicom project page ( https://github.com/fo-dicom/fo-dicom/ )
2. unzip fo-dicom-development.zip into somewhere appropriate (e.g. desktop)
3. open DICOM.Desktop.sln with Visual Studio (I use Visual Studio 2015)
4. build solution with configuration Debug, AnyCPU (should be default)
5. open Tools\Dicom Dump\Program.cs in Visual Studio
6. add `using System.Drawing;` at top of the file.
7. change Main function as following
```
        [STAThread]
        private static void Main()
        {
            Image image;
            using (var iimage = new Dicom.Imaging.DicomImage("sample.dcm").RenderImage())
            {
                image = iimage.As<Bitmap>();
            }

            var width = image.Width;

            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MainForm());
        }
```
8. save and close Program.cs
9. build Dicom Dump with configuration Debug, AnyCPU (should be default)
10. put dicom file into Tools\DICOM Dump\bin\Debug as "sample.dcm"
11. run Dicom Dump under Visual Studio
12. program would crash on `var width = image.Width;`
//

**Comment by mia-san** [comment] 2018-02-15 17:27
> I liked the idea that you showed in the example above: if you instanciate on DicomImage and call RenderImage() then every call to .AsBitmap returns the same image. Wouldn't that save a lot of memory?

yes, it saves a lot of memory.
but unfortunately, in WinForms, `System.Drawing.Image( or Bitmap)` is thin wrapper of unmanaged resource, namely GDI+.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms533798(v=vs.85).aspx

in previous case
```
var iimage = new DicomImage("dicom.file").RenderImage()
var bitmap1 = iimage.AsBitmap()
var bitmap2 = iimage.AsBitmap()
```
iimage, bitmap1 and bitmap2 shares same bitmap.
it means they shares same GDI+ object handle.
any one of those objects (including iimage) Disposed, all objects are now invalid.

similar to `System.IO.File` or such.


> You are very deep in the code now and know it very well: would you see a downside if WinformsImage would not dispose the member variable image? but let the GarbageCollector dispose it if there is no other Bitmap referencing this image?

that's not a good idea, I'm afraid.

1. WinFormsImage object may get GCed while some other part of program is still using the image.
this will delete underlying GDI+ object and causes "surprises".
2. creating a lot of WinFormsImage objects( e.g. for MR or CT studies ) may exhaust GDI+ resource before WinFormsImage objects get GCed.
3. leaving IDisposable object without Disposing is evil, right? :)

i.e. WinFormsImage object must NOT be GCed in case someone is still using the bitmap,
and of course, bitmap must NOT be disposed while someone is still using the same bitmap.
I think it's impractical.


> Otherwise I would prefer the Clone method. Since if you return a Bitmap with a memoryStream then the MemoryStream has to be open all the time. This would then not solve the disposing problem if the WinformsImage disposes the byte arrays or the MemoryStream.

yes, `Clone` should be better.
1. Cloning bitmap should be cheaper than creating new Bitmap.
2. you're right, MemoryStream implements IDisposable. we should Dispose it !!


> Will you create a pull-request? this issue is marked for the 4.0 release. Would be great if there was a solution soon.

OK, I've never created pull-request before, I'll try.
may take some time...

thanks.
//

**Comment by gofal** [comment] 2018-02-15 19:16
👍

**Comment by IanYates** [comment] 2018-02-16 11:54
Good points made here, and a horrible outcome to get a program crash :(
Having said that, see my notes on the PR.

Also
```
you're right, MemoryStream implements IDisposable. we should Dispose it !!
```
It does, but mostly only because `Stream` implements it.  `MemoryStream` Dispose() ends up marking it as non-writable but still keeps the memory anyway on purpose.  The GC will free it when nothing is pointing to it.  So it's not too much to stress about if trying to track the `MemoryStream` instance is going to cause trouble.  I guess there is that async cleanup bit it's doing so maybe there's some value there if there are async operations still involving the stream.
I guess an appeal to authority would help:  https://stackoverflow.com/a/234257/1053381 

ReferenceSource code for Dispose(bool)
```


        protected override void Dispose(bool disposing)
        { 
            try {
                if (disposing) { 
                    _isOpen = false; 
                    _writable = false;
                    _expandable = false; 
                    // Don't set buffer to null - allow GetBuffer & ToArray to work.
                }
            }
            finally { 
                // Call base.Close() to cleanup async IO resources
                base.Dispose(disposing); 
            } 
        }
 ```

**Comment by IanYates** [comment] 2018-02-17 12:58
Yeah I agree - keep it consistent :)

It sounded like tracking the reference to later Dispose() was difficult so I suggested if it was causing grief (and implicitly, if the MemoryStream was only internally constructed and referenced) then it needn't be stressed about too much.
But tracking for disposal is more consistent and saves people wondering in future why we're not disposing a particular stream.  It also means if the library ever allows plugging in something like https://github.com/Microsoft/Microsoft.IO.RecyclableMemoryStream then Dispose() is a must.

**Comment by IanYates** [comment] 2018-02-21 20:35
So I've been reading through this in conjunction with #651 

The problem with the originally posted code is that `DicomImage` is disposable.

Therefore this pattern
```
var img = dcm1.RenderImage().AsBitmap();
```

is dangerous.  The `DicomImage` returned by `dcm1.RenderImage()` is going to go out of scope eventually.  You're racing against the finalizer queue.  That race is being hastened by the call to `GC.Collect();`

PR #656 to fix this has my thoughts, admittedly not worth more than a lone voice who's been away from the project for too long, on the topic.  

However it's important to be clear about ownership of these unmanaged resources.

Borrowing code from @mia-san 

```
Image image;
using (var iimage = new Dicom.Imaging.DicomImage("sample.dcm").RenderImage())
{
  image = iimage.As<Bitmap>();
}
var width = image.Width;
```

That may or may not work at runtime.

This definitely won't work
```
Image image;
using (var iimage = new Dicom.Imaging.DicomImage("sample.dcm").RenderImage())
{
  image = iimage.As<Bitmap>();
}
GC.Collect();  //NEW LINE
var width = image.Width;
```

Either way it's ignoring the ownership of the bitmap and just disposing the `DicomImage`.  In some ways it's surprising, but it's also efficient at the moment and it'd be good to not lose the ability to avoid duplicate copies of `Bitmap` in memory for every invocation.

In the PR I've suggested that
a) users avoid the .As<> method.  `[Obsolete]` would work well here.
b) there are new extension methods added to let the caller get a bitmap they own, or one the `DicomImage` owns

There is still a fundamental bug here anyway - disposing `DicomImage` (by the use of the using statement above) ought to make the error occur regardless of the call to `GC.Collect()`.  It implies we're not cleaning up some internal resource on dispose, instead leaving it to the finalizer / GC.  It's nice that cleanup is still occurring, but it should also be deterministic when .Dispose() is being used.

**Comment by mia-san** [comment] 2018-02-21 21:03
```
Image image;
using (var iimage = new Dicom.Imaging.DicomImage("sample.dcm").RenderImage())
{
  image = iimage.As<Bitmap>();
}
var width = image.Width;
```
This is disposing `IImage` object which owns "bitmap", not `DicomImage`.
(`DicomImage` itself is not `Dispose()`-able).

`RenderImage()` returns `IImage`, which in turn `WinFormsImage` for WinForms environment, `WPFImage` for WPF environment.
They (`WinFormsImage` and `WPFImage`) both own "bitmap", they both are `Dispose()`-able.

so, above code reliably crash the program, with or without GC.Collect, as `IImage` returned by `RenderImage()` is immediately disposed on leaving `using()` construct, causing bitmap acquired by `As<Bitmap>()` to be invalidated.
//

**Comment by IanYates** [comment] 2018-02-22 06:15
You're 💯 right.
Sorry, I wrote my little test code a little bit differently after I blended it with the original code and then adapted to try to break it with your code.  You're right about DicomImage not being disposable.

I managed to make it still run occasionally without the GC.Collect, but that's just the race with the finalizer queue I *think*.

I'll have a dig into WinFormsImage later to get back up to speed on what it's doing.  Thanks!

**Closed** 2018-03-23 07:25 UTC
Labels: bug
