### ISSUE TITLE
Rescale Dicom Slice Quality, or reduce number of cols and rows

### ISSUE THREAD

**Issue by bocheta** [fo-dicom/fo-dicom#1478] opened 2022-11-28 15:40 UTC
**Describe the bug**
Hi Friends,
I want to rescale a dicom slice it has 1024 rows*1024 columns, which is to high resolution im my case. 
Is there any way to reduce the number of rows and columns? i tried to many things but still not working.

I hope you give me some ideas to achieve this.

Thank you so much.

**To Reproduce**
code i used, i tried to much solutions still now working
  var source = DicomFile.Open(file.FullName);
              
                    var sourcePixelData = DicomPixelData.Create(source.Dataset);
                
                    sourcePixelData.Height = 1000;
               
                    sourcePixelData.Width = 1000;
               
                    var t =sourcePixelData.UncompressedFrameSize;
                
                    var target = source.Clone();
                
                    var targetpixel = DicomPixelData.Create(target.Dataset);

**The broken dataset that i got**
![tt](https://user-images.githubusercontent.com/35003490/204318818-ce3c5907-2c30-435c-a9a1-5f31efe6a70e.PNG)

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.

**Environment**
Fellow Oak DICOM version: (e.g. 4.0.6)
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2)

**Comment by mrbean-bremen** [comment] 2022-12-01 09:45
Close as duplicate of #1480

**Closed as completed by mrbean-bremen** 2022-12-01 09:45 UTC
Labels: new
