### ISSUE TITLE
DicomServer.Dispose() does not close TCP listen connection.

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#158] opened 2015-12-02 16:43 UTC
After DicomServer is disposed the connection remains open until another client connection is established.  That client connection is processed and then the server connection is closed.  During the last client connection the: A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.dll is displayed in the console window.

**Comment by IanYates** [comment] 2015-12-03 11:25
I'll look at this along with #157 since they're in the same area

**Comment by IanYates** [comment] 2015-12-03 12:31
I think I can see the problem.

The change I plan on making in #157 will fix this too I believe.

The `Dispose()` method in `DicomServer<T>` sets the disposed flag to true.  However that flag is checked in the `Listen()` method's loop

```
                    do
                    {
                        try
                        {
                            var networkStream = listener.AcceptNetworkStream(certificateName, noDelay);

                            var scp = this.CreateScp(networkStream.AsStream());
                            if (this.Options != null) scp.Options = this.Options;

                            this.clients.Add(scp);
                        }
                        catch (Exception e)
                        {
                            this.Logger.Error("Exception accepting client {@error}", e);
                        }
                    }
                    while (!this.disposed);

                    if (listener != null)
                    {
                        listener.Stop();
                    }
```

The problem is that listener.AcceptNetworkStream() will block until there's a new connection to receive.  So the do/while loop is blocked until a client tries to connect.  When that happens the loop unblocks and the `while(!this.disposed)` check is processed, then the listener.Stop() method is finally called.

By hoisting listener up to be a class member we can change the synchronisation primitives used so that we can wait for a listener OR wait for disposal, etc.

**Comment by anders9ustafsson** [comment] 2015-12-07 20:58
@IanYates Again, well spotted! I still am not very fond of the idea of making `listener` a class member. Could it be an alternative to instead use a `CancellationTokenSource` as a class member, and add a `CancellationToken` to the `NetworkListener.AcceptNetworkStream` method signature? I haven't thought this through yet, but I am at least dropping the idea for others to think about.

**Comment by IanYates** [comment] 2015-12-08 00:29
Sure, I can try something along those lines.  Weekend was a bit crazy (spent all Saturday and Saturday night at dddbrisbane.com.au - good conference!) so I haven't written any code anyway.

**Comment by IanYates** [comment] 2015-12-12 11:06
@anders9ustafsson - have you already got code for this?

**Comment by anders9ustafsson** [comment] 2015-12-12 13:26
@IanYates Thanks for reviewing and merging #164. I am sorry for barging in like this, but I thought it would be good if we were able to make an official 2.0 release soon with these things fixed. 

No code yet for this one, so if you are still interested, please go ahead.

I have some thoughts along the lines I discussed earlier, let's see if you agree.

* In the `INetworkListener` interface, rename to `StartAsync` and `AcceptNetworkStreamAsync`, and have them return `Task` and `Task<INetworkStream>` respectively. This would better reflect that these methods need to make use of asynchronous calls internally. In the UWP implementation, the `Start` method is already now declared `async`, so this needs to be accounted for any way.
* As a consequence of having these methods returning `Task`s, the `Server.Listen` method should also be made `async`, and properly renamed.

Please let me know what you think, and if you want to deal with it. Otherwise it is no problem for me to give this one a try myself.

**Closed** 2015-12-15 06:00 UTC
Labels: bug, in progress
