### ISSUE TITLE
Connection from Modality getting very unreliable to the Fo-Dicom based StoreSCP

### ISSUE THREAD

**Issue by Smithangshu** [fo-dicom/fo-dicom#1120] opened 2020-10-12 12:09 UTC
**Describe the bug**
Modality failed to connect the StoreSCP

**To Reproduce**
```C#
       private static readonly DicomTransferSyntax[] AcceptedTransferSyntaxes = new DicomTransferSyntax[]
            {
                DicomTransferSyntax.ExplicitVRLittleEndian,
                DicomTransferSyntax.ExplicitVRBigEndian,
                DicomTransferSyntax.ImplicitVRLittleEndian
            };
        private static readonly DicomTransferSyntax[] AcceptedImageTransferSyntaxes = new DicomTransferSyntax[]
        {
               // Lossless
               DicomTransferSyntax.JPEGLSLossless,
               DicomTransferSyntax.JPEG2000Lossless,
               DicomTransferSyntax.JPEGProcess14SV1,
               DicomTransferSyntax.JPEGProcess14,
               DicomTransferSyntax.RLELossless,
               // Lossy
               DicomTransferSyntax.JPEGLSNearLossless,
               DicomTransferSyntax.JPEG2000Lossy,
               DicomTransferSyntax.JPEGProcess1,
               DicomTransferSyntax.JPEGProcess2_4,
               // Uncompressed
               DicomTransferSyntax.ExplicitVRLittleEndian,
               DicomTransferSyntax.ExplicitVRBigEndian,
               DicomTransferSyntax.ImplicitVRLittleEndian,

               DicomTransferSyntax.MPEG2,
               DicomTransferSyntax.MPEG2MainProfileHighLevel,
               DicomTransferSyntax.MPEG4AVCH264BDCompatibleHighProfileLevel41,
               DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41,
               DicomTransferSyntax.MPEG4AVCH264HighProfileLevel42For2DVideo,
               DicomTransferSyntax.MPEG4AVCH264HighProfileLevel42For3DVideo,
               DicomTransferSyntax.MPEG4AVCH264StereoHighProfileLevel42,

               DicomTransferSyntax.XMLEncoding,
               DicomTransferSyntax.RFC2557MIMEEncapsulation,
               DicomTransferSyntax.HEVCH265Main10ProfileLevel51,
               DicomTransferSyntax.HEVCH265MainProfileLevel51
        };

        public StoreSCP(INetworkStream stream, Encoding fallbackEncoding, Logger log) : base(stream, fallbackEncoding, log)
        {
        }

        public Task OnReceiveAssociationRequestAsync(DicomAssociation association)
        {
            DataTable dtAET = SQLiteDBAccess.GetData("Select SettingValue From tblServerSettings Where SettingKey='AET'");
            if (dtAET != null && dtAET.Rows.Count > 0)
            {
                string AET = Convert.ToString(dtAET.Rows[0]["SettingValue"]);
                if (association.CalledAE != AET)
                {
                    WriteLog("Association request rejected. Calling AET:" + association.CallingAE + " Called AET:" + association.CalledAE);
                    return SendAssociationRejectAsync(
                        DicomRejectResult.Permanent,
                        DicomRejectSource.ServiceUser,
                        DicomRejectReason.CalledAENotRecognized);
                }

                foreach (var pc in association.PresentationContexts)
                {
                    if (pc.AbstractSyntax == DicomUID.Verification) pc.AcceptTransferSyntaxes(AcceptedTransferSyntaxes);
                    else if (pc.AbstractSyntax.StorageCategory != DicomStorageCategory.None) pc.AcceptTransferSyntaxes(AcceptedImageTransferSyntaxes);
                }
                WriteLog("Association request accecpted. Calling AET:" + association.CallingAE);
                return SendAssociationAcceptAsync(association);
            }
            else
            {
                return SendAssociationRejectAsync(
                        DicomRejectResult.Permanent,
                        DicomRejectSource.ServiceUser,
                        DicomRejectReason.CalledAENotRecognized);
            }
        }
        public Task OnReceiveAssociationReleaseRequestAsync()
        {
            return SendAssociationReleaseResponseAsync();
        }

        public void OnReceiveAbort(DicomAbortSource source, DicomAbortReason reason)
        {
            WriteLog("Receive aborted. Source:" + source + ", Reason:" + reason.ToString());
        }

        public void OnConnectionClosed(Exception exception)
        {
            WriteLog("Connection closed. Exception:" + exception.Message);
        }

        public DicomCStoreResponse OnCStoreRequest(DicomCStoreRequest request)
        {
            try
            {
                WriteLog("CStoreRequest received. SOP UID:" + request.SOPInstanceUID.UID);
                DicomImage dcm = new DicomImage(request.File.Dataset);
                DicomFile dcmFile = request.File;
                //StoreThread(dcm, dcmFile);
                var t = new Thread(() => StoreThread(dcm, dcmFile)) { IsBackground = true };
                t.Join();

                return new DicomCStoreResponse(request, DicomStatus.Success);
            }
            catch (Exception ex)
            {
                WriteLog("CStoreRequest error:" + ex.Message);
                return new DicomCStoreResponse(request, DicomStatus.ProcessingFailure);
            }
        }
```

**Expected behavior**
It should successfully connect associate and transfer files to FO-Dicom Server

**Screenshots or test DICOM files**
Setting on the Modality
![IMG-20201011-WA0001](https://user-images.githubusercontent.com/30255929/95744650-46b5db00-0cb1-11eb-99da-793baf0e07a6.jpg)
Message what I am getting from the Modality
![IMG-20201011-WA0000](https://user-images.githubusercontent.com/30255929/95744725-71079880-0cb1-11eb-9289-1328e2f00d4c.jpg)

**Environment**
Fellow Oak DICOM version: 4.0.3
OS: Windows 7 x64
Platform: .NET Framework 4.7.2

Please help me to sort out the issue. I am facing this issue every 2nd testing environment. Whereas other Dicom servers on that same machine with same modality is working fine. So I really need your help to get rid of this issue.

**Comment by mia-san** [comment] 2020-10-16 06:10
just curious, what happens if you comment out following 2 lines ?
connection become reliable?
it would be first step to tell where the problem is,  fo-dicom or your code.

```var t = new Thread(() => StoreThread(dcm, dcmFile)) { IsBackground = true };
t.Join();```
//

**Comment by Smithangshu** [comment] 2020-10-16 23:46
Well actually I had to add it by need not choice. Before that it was single threaded but problem happens when I found StoreThread method is taking longer time since it has db interaction so it took some time before sending back the acknowledgment response to the Modality and due to that some Modality acts weirdly like issuing some error message on its console. That's why multi-threading was introduced on that point so that asap we can send the response back to the Modality and rest of the operations can be taken place on the different thread.

Is there any way out to avoid multi-threading there?

**Comment by mia-san** [comment] 2020-10-17 00:34
I know you have a purpose for multi-threading, just wanted to isolate where the problem comes from.

btw, is the modality in question CT or MRI ?
or even CR causes trouble ?

also anything logged on your c-store server at failure?

well, making 'db interfaction' faster would be real cure, but sometimes there's no choice... :)
//

**Comment by Smithangshu** [comment] 2020-10-17 07:34
Same issue even after removing the part you mentioned.

Modality is CT.

Actually no failure is detected on my side, when modality sends the images it first told me about the Association Requested.
Then on the very next moment it receives Release Request from the Modality and then validate Release Request and sends Release Response.

By the way if I test it with DVTK Store SCU emulator it works fine every time. But with real Modality on some PC it works and on some other it does not. Although I checked that Association Request is received so hopefully there is no port firewall/network issue. But other software on the same machine works correctly.

**Comment by mia-san** [comment] 2020-10-19 04:49
have you checked what the modality is proposing in presentation context on association ?
your observation sounds like modality is giving up at association before actually starting c-store.

also, you may want to enable fo-dicom's logging facility.
https://github.com/fo-dicom/fo-dicom#logging-configuration
//

**Comment by Smithangshu** [comment] 2020-10-19 14:01
Hi,
Can you please suggest me how can I check "what the modality is proposing in presentation context on association ?"?
Yes I think you are right but I am clueless about how to fix it and since the other software works correctly on the same machine with same modality so client is not ready to hear my excuses.

With default logging problem is logging libraries are very large in size so its very difficult for me transfer that over network to the client place and since my project is in development so each time if I change anything I need to send again the new version with such huge data to client over network that's why I went for custom logging which I made for the project as you see on the above code.

**Comment by mia-san** [comment] 2020-10-19 16:40
what about just print everyting in presentation context into logging ?
probably something like
```
foreach (var pc in association.PresentationContexts)
{
    WriteLog(pc.AbstractSyntax.UID);
    foreach (var ts in pc.GetTransferSyntaxes())
    {
        WriteLog($"  {ts.UID.UID}");
    }
}
```
//

**Comment by Smithangshu** [comment] 2020-10-21 05:51
Hi, thanks for the idea. Since my client testing center has got Covid affected so now we can not test it immediately. But please don't close the thread as soon as we are ready to test I will reply with the feedback.

**Comment by mia-san** [comment] 2020-10-21 12:44
ok, please take care :)

**Comment by gofal** [comment] 2024-03-25 09:39
Closing this due to incactivity.
If with the latest version of fo-dicom there is still this issue, please reopen this issue and provide actual information.

**Closed by gofal** 2024-03-25 09:39 UTC
Labels: evaluating
