### ISSUE TITLE
Dicom tag validation accepts empty component for UIDs 

### ISSUE THREAD

**Issue by JuanNuri** [fo-dicom/fo-dicom#1503] opened 2023-01-30 09:48 UTC
### Expected behavior
validation of tags with VR UI returns an error when there is an empty component (example: ".1.2.3", "1.2.3." and "1..2.3" )

### Actual behavior
Such values are considered valid

### Steps to reproduce the behavior

static public void Validate(DicomDataset dataset){
    foreach (var element in dataset)    {
        newDataset.Add(element);
    }
}
[Fact]
public void TestUIValidation(){
    var dataset = new DicomDataset().NotValidated();
    dataset.AddOrUpdate<string>(DicomTag.StudyInstanceUID, ".1.2.3");
    dataset.AddOrUpdate<string>(DicomTag.SeriesInstanceUID, "1..2.3");
    var exception = Record.Exception(() => Validate(dataset));
    Assert.NotNull(exception);
}

### fo-dicom version and OS/platform
fo-dicom 5.0.3
OS : linux and windows

**Comment by mrbean-bremen** [comment] 2023-01-30 12:15
Actually I'm not sure if these are valid. The standard says:

> The UID is a series of numeric components separated by the period "." character.

Which in my understanding does not allow for empty components. I have never seen such values, but I'm pretty sure that it is at least not allowed to start a UI value with a period. Do you have any reference that says otherwise?

**Comment by olivier-med** [comment] 2023-01-31 12:05
The problem is that the values stating with a dot or with an empty group x..y are accepted by the UI validation.

the fix should be something like

> if (Regex.IsMatch(content, @"^[.]") || Regex.IsMatch(content, @"[.][.]+") || Regex.IsMatch(content, @"[.]$"))
> {
>    throw new DicomValidationException(content, DicomVR.UI, "a group can not be empty");
>}

to be added to the function public static void ValidateUI(string content)

We've got some series (very few, from a single hospital) with such UI values.

**Comment by olivier-med** [comment] 2023-01-31 12:07
In addition, accepting an empty UI should not be the correct validation I think.

**Comment by mrbean-bremen** [comment] 2023-01-31 19:55
> The problem is that the values stating with a dot or with an empty group x..y are accepted by the UI validation.

Sure - sorry, I misread the first time for some reason - you are right of course. The validation logic should be fixed. Are you planning to make a PR for this?

> In addition, accepting an empty UI should not be the correct validation I think.

Any type 2 or 3 tag may be empty, and as we do not check the context where the tags are used (e.g. we don't know if a tag is a type 1 tag for a given IOD), I think that we have to assume that any tag may be empty. 
We know of course that several UIDs must not be empty (like SOPInstanceUID or SOPClassUID), but these would have to be checked specifically, not in the general validation code that only looks for valid values for the VRs.
Unless I'm missing something again of course...

**Comment by olivier-med** [comment] 2023-02-01 09:21
Hello, yes I can make a PR with the fix above.

**Comment by olivier-med** [comment] 2023-02-01 14:50
Here is the [PR](https://github.com/fo-dicom/fo-dicom/pull/1509)

**Comment by gofal** [comment] 2023-02-09 06:51
fixed by PR #1509

**Closed as completed by gofal** 2023-02-09 06:51 UTC
