### ISSUE TITLE
CSTORE SCP Occasionally Stops Receiving Requests Until Service Is Restarted

### ISSUE THREAD

**Issue by ajbatta** [fo-dicom/fo-dicom#1450] opened 2022-09-20 13:39 UTC
**Describe the bug**
We have a .NET 6 Windows Worker Service running a CSTORE CSP server that will randomly stop receiving requests until the service is restarted. Nothing is written in the logs when this occurs besides random 0 byte requests that are closed by the library, which I believed are caused by a endpoint check.

**To Reproduce**
There's not easy way to reproduce the issue besides running the service for a few days.

**Expected behavior**
CSTORE SCP server is able to continuously receive requests.

![image](https://user-images.githubusercontent.com/100306760/191272838-c4e11829-3b93-41f5-b803-deb27e2ade19.png)

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 10 VM
Platform: .NET 6

**Comment by gofal** [comment] 2022-10-03 07:48
There is not too much information. but one code smell, that I see is the following:
The WorkerService is instanciated ad ExecuteAsync is called. There you are starting a new task. within this task you create a server. This server-creating task will termine. So all local variables of that task will go out of scope and eventually cleaned up by garbage collector. Since the server instance, that you created win _dicomServerFactory.Create is not referenced somewhere else, this object is unreferenced and disposed. 
You should move the local variable "var server = _dicomServerFactory..." into a class variable of the worker. So the worker has the class variable "IDicomServer _server;" and then you call "_server = _dicomServerFactory.Create...". 
You will need that reference anyway, becase the worker will get some event when the worker will stop, and there you should call "_server?.Dispose()".

**Comment by ajbatta** [comment] 2022-10-03 13:03
@gofal thank you for your help! This might be a dumb question, but when I register the cancellationToken to call server.Dispose() when the worker service is stopped will that not keep the server object from being collected by the GC since it's referenced?Thanks again!

**Comment by gofal** [comment] 2022-10-03 13:12
No, not necessarily. The asp.net infrastructure creates a canellationtoken to start executing all the registered workers. But the infrastructure may dispose this token any time for some reason you cannot control. So agree, asp.net will keep this token for some while and therefore the server is referenced somehow and therefore your application might work most of the time. But you cannot rely on that. Thats propably why you occasionally do have this issue here

**Comment by ajbatta** [comment] 2022-10-03 13:24
Aaah ok that makes sense. Thank you for explaining that! So another thing I noticed is that the issue seems to occur when I get  these weird "Read 0 bytes from network stream while reading PDU, connection will be marked as closed" connections that I believe are caused by a load balancer pinging the port, but I'm not 100% sure. Could this maybe be related or probably not?

**Comment by gofal** [comment] 2022-11-22 15:19
i doubt that is is related. with every new socket connection the server creates a new instance of DicomService (or an inherited class) and this instance then does the processing. When an association crashes then this usually happens within the DicomService and not the DicomServer. But of course everything is possible.

**Comment by ajbatta** [comment] 2022-11-22 15:32
Thanks for the information!Is there a good way to troubleshoot these kinds of issues? On Nov 22, 2022, at 7:19 AM, Reinhard Gruber ***@***.***> wrote:﻿
i doubt that is is related. with every new socket connection the server creates a new instance of DicomService (or an inherited class) and this instance then does the processing. When an association crashes then this usually happens within the DicomService and not the DicomServer. But of course everything is possible.

**Comment by gofal** [comment] 2022-11-22 16:52
I assume you already have a ILogger instance assigned to the DicomServer? Because this would be the first thing to do

**Comment by ajbatta** [comment] 2022-11-22 17:03
Yup, have the ILogger setup and configured with Serilog.Nothing really shows up in the logs which is weird.On Nov 22, 2022, at 8:52 AM, Reinhard Gruber ***@***.***> wrote:﻿
I assume you already have a ILogger instance assigned to the DicomServer? Because this would be the first thing to do

**Comment by amoerie** [comment] 2022-12-07 09:31
You're configuring MaxClientsAllowed with a value of 2.
That means only 2 active connections may exist at all times.
If you try to open a third connection, you will be stuck at this line:

https://github.com/fo-dicom/fo-dicom/blob/e48e18572544fb5fce2b61a949731256361a906c/FO-DICOM.Core/Network/DicomServer.cs#L283

We could improve logging here to print out a warning log every minute while we're stuck here, to help diagnose this issue.
However, the root cause will be elsewhere, i.e. services not being cleaned up properly.

**Comment by ajbatta** [comment] 2022-12-08 02:20
Hi,Thanks for the information. So in this situation would the 3rd connection sit there until a connection drops off? Or would the CSTORE request fail or hang indefinitely?We’re seeing behavior where our 3rd party service provider Ambra’s requests to our Dicom service hangs indefinitely until we either restart their service or ours.Thanks again for your help!- AndrewOn Dec 7, 2022, at 1:31 AM, Alexander Moerman ***@***.***> wrote:﻿
You're configuring MaxClientsAllowed with a value of 2.
That means only 2 active connections may exist at all times.
If you try to open a third connection, you will be stuck at this line:
https://github.com/fo-dicom/fo-dicom/blob/e48e18572544fb5fce2b61a949731256361a906c/FO-DICOM.Core/Network/DicomServer.cs#L283
We could improve logging here to print out a warning log every minute while we're stuck here, to help diagnose this issue.
However, the root cause will be elsewhere, i.e. services not being cleaned up properly.

**Comment by amoerie** [comment] 2023-05-26 12:55
> Hi,Thanks for the information. So in this situation would the 3rd connection sit there until a connection drops off? Or would the CSTORE request fail or hang indefinitely?We’re seeing behavior where our 3rd party service provider Ambra’s requests to our Dicom service hangs indefinitely until we either restart their service or ours. Thanks again for your help

Hi @ajbatta we have released 5.1.0 with improved logging in this area. Feel free to give this another spin and please tell us the results.

**Comment by amoerie** [comment] 2023-05-31 06:59
@ajbatta Just another update, we found an actual issue related to MaxClientsAllowed.
You can wait for the next fo-dicom release where this issue will be fixed (see https://github.com/fo-dicom/fo-dicom/pull/1602) or you can set the MaxClientsAllowed setting to 0 to circumvent the issue for now.

**Comment by amoerie** [comment] 2023-08-23 08:48
I believe this will be fixed with the next release. Please open a new issue if it still occurs then.

**Closed as completed by amoerie** 2023-08-23 08:48 UTC
Labels: question
