### ISSUE TITLE
Unable to build fo-dicom based applications for UWP with .NET Native toolchain

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#424] opened 2017-02-03 11:18 UTC
### Expected behavior
It should be possible to build UWP applications referencing *fo-dicom.Universal* with the .NET Native toolchain enabled.

### Actual behavior
Build error:
> Error MCG0017: MCG0017:NotWinRTType Cannot marshal generic Windows Runtime types with a non Windows Runtime type as a generic type argument. Check the generic arguments of type 'System.Collections.Generic.KeyValuePair`2<Dicom.DicomTag, Dicom.DicomItem>'.

### Steps to reproduce the behavior
Build *fo-dicom.Universal* based UWP application with .NET Native toolchain enabled for arbitrary platform.

### fo-dicom version and OS/platform
3.0.0-rc2, Universal Windows Platform

**Comment by anders9ustafsson** [comment] 2017-02-08 14:59
The build error refers to the private item collection in `DicomDataset`, which is declared `IDictionary<DicomTag, DicomItem>`. Since `DicomTag` and `DicomItem` are in fact not Windows Runtime types, the mapping for runtime type `Windows.Foundation.Collections.IKeyValuePair<K, V>` will fail (see [here](https://msdn.microsoft.com/en-us/library/hh995050.aspx)).

In principle, it would make perfect sense to represent the item collection as an `ISet<DicomItem>` instead. That would solve the above problem, but unfortunately lead to another (hard to solve) build error:

> Internal compiler error: Unable to cast object of type 'Mcg.CodeGen.MarshallerData' to type 'Mcg.CodeGen.ComClassMarshallerData'.

There are also a large collection of build warnings associated with the .NET Native tool chain (excerpt from x64 build):

>1>D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom-samples\Universal\SimpleViewer.Universal\ByteBufferEnumerator.cs(39,39): warning : GK0006 Delegate 'System.IAsyncResult Dicom.IO.ByteSourceCallback.BeginInvoke(Dicom.IO.IByteSource, System.Object, System.AsyncCallback, System.Object)' is not yet implemented.
1>D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom-samples\Universal\SimpleViewer.Universal\ByteBufferEnumerator.cs(44,9): warning : GK0006 Delegate 'System.Void Dicom.IO.ByteSourceCallback.EndInvoke(System.IAsyncResult)' is not yet implemented.
1>  Processing application code
1>D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom-samples\Universal\SimpleViewer.Universal\Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
1>D:\Users\Anders\Documents\Visual Studio 2013\Projects\fo-dicom-samples\Universal\SimpleViewer.Universal\Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform_0027: Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.
1>  Computing application closure and generating interop code
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0000: [MarshalAs(UnmanagedType=(Default), ElementType=(Default))] with type 'System.Byte[]' is deprecated.This signature is located on 'System.Byte[] Dicom.IO.Buffer.IByteBuffer.Data.get()'.Additional information: Marshalling array as SAFEARRAY is deprecated.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0000: [MarshalAs(UnmanagedType=(Default), ElementType=(Default))] with type 'System.Byte[]' is deprecated.This signature is located on 'System.Byte[] Dicom.IO.Buffer.IByteBuffer.GetByteRange(System.Int32, System.Int32)'.Additional information: Marshalling array as SAFEARRAY is deprecated.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IList`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IList`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.ICollection`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.ICollection`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerable`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerable`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.IEnumerable'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.IEnumerator'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerator`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerator`1<System.UInt32>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.IDisposable'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IList`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IList`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.ICollection`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.ICollection`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerable`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerable`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerator`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerator`1<Dicom.IO.Buffer.IByteBuffer>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IList`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IList`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.ICollection`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.ICollection`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerable`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerable`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerator`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerator`1<Dicom.DicomDataset>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.ISet`1<Dicom.DicomItem>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.ISet`1<Dicom.DicomItem>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.ICollection`1<Dicom.DicomItem>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.ICollection`1<Dicom.DicomItem>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerable`1<Dicom.DicomItem>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerable`1<Dicom.DicomItem>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'System.Collections.Generic.IEnumerator`1<Dicom.DicomItem>'.
1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x64\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0007: Generic types are not supported for COM and platform invoke interoperability. To stop seeing this warning, try removing generic arguments from type or interface 'System.Collections.Generic.IEnumerator`1<Dicom.DicomItem>'.

**Comment by anders9ustafsson** [comment] 2017-02-08 15:02
So to conclude, the current standpoint is that this is not something that can be easily fixed in code.

Instead, the take-away message for the time being is that *fo-dicom* based *Universal Windows Platform* applications currently cannot be built with the .NET Native tool chain enabled.

Eventually, this issue should be fixed programmatically, but for version 3.0 we will leave the issue without further notice.

**Comment by thewordofb** [comment] 2017-02-15 13:36
I've not tried disabling the .NET Native toolchain yet, but my understanding is this will fail certification in the app store.

**Comment by anders9ustafsson** [comment] 2017-02-15 13:41
@thewordofb OK, sounds reasonable, and that of course makes it all the more important to solve this issue. Will prioritize it. And if you have any input on how to overcome the problem, don't hesitate to let me know.

**Comment by anders9ustafsson** [comment] 2017-02-15 14:46
@thewordofb Do you have any previous experience with issues like this? The construct the compiler is complaining about, i.e. `System.Collections.Generic.KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>` is only used privately inside the `DicomDataset` class. As far as I know, this generic type is never exposed in an API, so it is not obvious to me why it can't be compiled into native code? What am I missing?

**Comment by gustavosaita** [comment] 2017-02-17 19:43
Hi guys!

First of all I would really like to thank @anders9ustafsson and all developers of fo-dicom by all hard work on the lib.
It's currently an amazing lib and it's getting better and better.
A lot of physician and health related people are being benefited by fo-dicom.

I was facing a lot of problems (other problems) after installing Windows 10 SDK 10.0.14393.795.
Finally, I removed all SDKs and reinstall VS 2015 (with 10.0.14393.795 SDK)

So, I started to have the same problem as you:
"Error MCG0017: NotWinRTType Can not marshal generic Windows Runtime types with a non Windows Runtime type a generic type of argument 'System.Collections.Generic.KeyValuePair`2 <Dicom.DicomTag, Dicom.DicomItem> '. "

Well, before, I did not change anything in my project and I was able to build my app using fo-dicom 3.0 and submit a UWP app to Windows Store successfully. 
So, I removed SDK 10.0.14393.795 but I'm still with the same problem.
I still not figure out what is going on...

Well, if I have some news I let you know.

Thank you guys and good luck for us :)

**Comment by gustavosaita** [comment] 2017-02-18 22:10
Dear all,

I found a specific environment that fo-dicom 3.0 can be compiled with ".NET Native toolchain enabled".
But it appears that is some bug (with a good side-effect) of Microsoft that enables you to compile it. (I really have no idea why this works) 

- VS Professional 2015 Update 1 (I believe any version with only Update 1)
- Windows 10 SDK 10.0.26624
- Windows 10 SDK 10.0.10586.15
- VS Tools for UWA 14.0.24720.00
- NuGet 3.3.0
 
I still didn't try to submit to Windows Store but at least it compiles :)
Thank you guys.

**Comment by 1danielcoelho** [comment] 2017-02-19 15:05
Replacing the Windows Runtime IDictionary and SortedDictionary with a custom dictionary class does "solve" the initial build error

`Error MCG0017: MCG0017:NotWinRTType Cannot marshal generic Windows Runtime types with a non Windows Runtime type as a generic type argument. Check the generic arguments of type 'System.Collections.Generic.KeyValuePair2<Dicom.DicomTag, Dicom.DicomItem>'.`

The second build error, 

`Internal compiler error: Unable to cast object of type 'Mcg.CodeGen.MarshallerData' to type 'Mcg.CodeGen.ComClassMarshallerData'.`

occurs specifically because of line 444:

`return element.Get<T>(n);`

Commenting out this line allows the library to be used in a UWP project, sadly breaking critical functionality.

This seems to be some form of WinRT internal error, since the only result Google ever returns for the queries "Mcg.CodeGen.MarshallerData" or "Mcg.CodeGen.ComClassMarshallerData" is this very thread.

**Comment by anders9ustafsson** [comment] 2017-02-19 22:00
Many thanks @gustavosaita and @1danielcoelho for your invaluable input on this. I will use your input to see how much further I can move with this issue. @1danielcoelho custom dictionary you say, is it a dictionary that does not implement `IDictionary<TKey, TValue>`, or?

**Comment by 1danielcoelho** [comment] 2017-02-19 22:16
If you create another dictionary implementation (without inheriting from any WinRT types) with internal arrays of `TKey` and `TValues` and manual automatic resizing (obviously can't use `List<T>` here either), it has no reason to produce that error, since it allows non-WinRT types to be generics of non-WinRT types. 

I think for this workaround to work you might have to change `_items` to a direct reference of your dictionary implementation, as opposed to a reference to an interface that it implements, but I'm not sure.

This feels really ad-hoc (the dictionary would be used just for this) and kind of against C# style guides. On top of that you would still have to handle that unparseable error message about MarshallerData.

If I had to guess I would say that WinRT is getting confused as to how to marshal that `element.Get<T>(n)` term, since it itself is a generic abstract method that returns T. Can't seem to be getting anywhere however.

**Comment by thewordofb** [comment] 2017-02-22 02:14
Okay, I've been messing with this in my free time for a couple days and I got tired of guessing so I just emailed the .NET Native toolchain team at Microsoft with this thread.  My guess is something happened when the toolchain upgraded to 1.6.  I'll let everyone know if I get a response.

**Comment by MattWhilden** [comment] 2017-02-22 03:08
Hello! I work on the .NET Native compiler team. I'm able to reproduce the error locally (with v3.0.0 from Nuget). I'm heading out for the day but will take a look at this more deeply tomorrow and let you know what comes up.

Hopefully we'll be able to get it sorted out shortly and get everyone back on their way. Thanks for taking the time to reach out. We're happy to help.

**Comment by anders9ustafsson** [comment] 2017-02-27 07:54
@MattWhilden Thanks for offering to help us with this! Have you been able to find any explanation why our code don't compile to .NET Native?

**Comment by MattWhilden** [comment] 2017-03-01 01:15
Yep. I have someone from the .NET Native Interop team actively engaged on this. Will post and update soon. If you discover that I've disappeared for a while please feel free to ping me. I'd hate for y'all to get abandoned because I got distracted (read:swamped) with other investigations. :-) "Squeaky wheels..." and all that.

**Comment by shrah** [comment] 2017-03-01 20:52
Thank you for your patience. This is a known issue in .NET Native which has recently been fixed. At compile time .NET Native tries to analyze the set of types which may be needed at runtime and in the process erroneously identified some items as MarshalStructure. As a workaround you can add the following in your Default.rd.xml:

```
    <Type Name="System.Collections.Generic.IDictionary{Dicom.DicomTag, Dicom.DicomItem}" MarshalStructure="Excluded" />
    <Type Name="System.Collections.Generic.IList{Dicom.DicomDataset}" MarshalStructure="Excluded" />
    <Type Name="System.Collections.Generic.IList{Dicom.IO.Buffer.IByteBuffer}" MarshalStructure="Excluded" />
    <Type Name="System.Collections.Generic.IList{System.UInt32}" MarshalStructure="Excluded" />

```
Let me know if it works for you.

**Comment by anders9ustafsson** [comment] 2017-03-01 22:14
Many thanks, @shrah. I'll give it a try asap. Maybe a stupid question, but should the directives go into the rd.xml file of the class library or the application?

**Comment by shrah** [comment] 2017-03-01 22:39
Ideally it shouldn't matter. May be you can try the application one.

**Comment by 1danielcoelho** [comment] 2017-03-01 23:29
We were getting that problem while compiling Fodicom's class libraries themselves though, so I guess you'd need these directives in your DICOM.Windows project somewhere. In this case the file might be called Dicom.Platform.rd.xml, but I'm not really sure.

**Comment by MattWhilden** [comment] 2017-03-02 00:55
One way to apply the workaround would be to have each UWP application add these directives into their Properties\Default.rd.xml file. That's super clunky and leads to downstream consumers of layers of libraries needing to do a lot more leg work. Fortunately, the compiler will scan your project for any file that matches *.rd.xml and abide by directives in it. My suggestion would be to add a it to the project (and Nuget package) that these types live in. This will cause all consumers of that library to automatically get the workaround.

Does that help clarify?

**Comment by anders9ustafsson** [comment] 2017-03-03 10:37
Fantastic, it works! Many thanks, @shrah and @MattWhilden !

A few more questions:

1. I still get the warning message below when I build. Can I formulate a directive to get rid of this warning as well?

> 1>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(936,5): warning : ILTransform_0000:       MCG : warning MCG0002: "COM and Windows Runtime interfaces require a GUID. Add System.Runtime.InteropServices.GuidAttribute(...) or Windows.Foundation.Metadata.GuidAttribute to interface 'Dicom.IO.Buffer.IByteBuffer'.

2. The issue has recently been fixed, you say. Does that mean that with the upcoming VS 2017 release we can remove these directives again? Will the fix also be migrated to VS 2015?

3. Is there a repository e.g. of sample .rd.xml files around that could practically show how to configure these files correctly? I know there is MSDN documentation on the runtime directives, but it would help a lot to also have real-time examples to look at.

**Comment by MattWhilden** [comment] 2017-03-03 21:45
I'll defer to @shrah to 1+2 but here's some more resources that talk about rd.xml files:
https://blogs.msdn.microsoft.com/dotnet/2014/05/20/net-native-deep-dive-dynamic-features-in-static-code/
https://blogs.msdn.microsoft.com/dotnet/2014/05/23/net-native-deep-dive-making-your-library-great/
https://blogs.msdn.microsoft.com/dotnet/2014/05/24/net-native-deep-dive-optimizing-with-runtime-directives/

**Comment by shrah** [comment] 2017-03-03 23:36
1. If the specified type is passed to COM/WinRT then you want to define a GUID for the type. If it is for plain P/Invoke, you can safely ignore the warning. Adding following to your csproj file will ignore the warning:
 ```
 <PropertyGroup>
    <IlcParameters> /SuppressWarnings:ILTransform_0000</IlcParameters>
  </PropertyGroup>
```
Note, it will suppress  all warnings with code ILTransform_0000.

2.  It will not be available in VS 2017 RTM. The fix is in the development branch and we don't have a definite shipping date for it yet. We will share more information as the shipping schedule is finalized. Sorry for your inconvenience.

**Comment by anders9ustafsson** [comment] 2017-03-05 15:33
Thanks for the update, @shrah. Very grateful for all your help with this.

**Closed** 2017-03-05 15:53 UTC
Labels: enhancement, in progress

**Comment by gustavosaita** [comment] 2017-03-06 21:58
That's a really great notice!
Thank you very much @MattWhilden @shrah and @anders9ustafsson.
It works beautifully.
