### ISSUE TITLE
NullReferenceException DicomDirectory.AddFile()

### ISSUE THREAD

**Issue by patachi** [fo-dicom/fo-dicom#1549] opened 2023-04-25 23:50 UTC
**Describe the bug**
Adding the 2nd file in the for-each loop will throw the exception.

**Test DICOM files**
[Covid Scans](https://singularhealth-my.sharepoint.com/:f:/g/personal/jhill_singular_health/EvDEbleOjp5Cv53zGEmw2PkBf8tLiYcEOb_SOjzss-PK5Q?e=FGkapP) (from [website](https://3dicomviewer.com/dicom-library/)) 

**To Reproduce**

```
var path = @"C:\Samples\Covid Scans\Subject (1)\98.12.2";
var ddir = new DicomDirectory();
foreach (var filePath in Directory.GetFiles(path))
{
    try
    {
        var f = DicomFile.Open(filePath);
        ddir.AddFile(f);
    }
    catch (FellowOakDicom.DicomFileException ex)
    {
        Console.WriteLine($"WARNING : invalid DICOM file {filePath}");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"ERROR : {ex.Message}");
        Console.WriteLine($"ERROR StackTrace:{Environment.NewLine + ex.StackTrace}");
    }
}
```
```
ERROR : Object reference not set to an instance of an object.
ERROR StackTrace:
   at FellowOakDicom.DicomPersonName.get_Last()
   at FellowOakDicom.DicomPersonName.HaveSameContent(DicomPersonName nameA, DicomPersonName nameB)
   at FellowOakDicom.Media.DicomDirectory.CreatePatientRecord(DicomDataset dataset)
   at FellowOakDicom.Media.DicomDirectory.AddNewRecord(DicomFileMetaInformation metaFileInfo, DicomDataset dataset, String referencedFileId)
   at FellowOakDicom.Media.DicomDirectory.AddFile(DicomFile dicomFile, String referencedFileId)
```

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 11 x64
Platform: Tested on both .NET Core 7.0 & .NET Framework 4.8

**Comment by mrbean-bremen** [comment] 2023-04-26 06:24
As far as I can see, there is no DICOM directory (DICOMDIR) in your data, so you can't access it.
You probably just want to iterate over the files in the filesystem directory instead of using `DicomDirectory`.

**Comment by patachi** [comment] 2023-04-26 08:22
@mrbean-bremen The supposed behavior for `DicomDirectory` is to automatically generate `PATIENT > STUDY > SERIES > IMAGE records` based on the metadata of each DICOM file that it receives and put them in the correct position.

This behavior **is working correctly** but for this DICOM file it encountered an exception, so I just provide it for more inspection.

**Comment by mrbean-bremen** [comment] 2023-04-26 09:43
Ah, sorry - my bad, I mis-read the code. You are right, of course.

**Comment by mrbean-bremen** [comment] 2023-04-30 11:26
After investigating this a bit more I realized that it is already fixed in the development branch, but not yet in a release. This looks like a duplicate of #1405.

**Closed as completed** 2024-01-11 21:30 UTC
Labels: question
