### ISSUE TITLE
Get(DicomTag.LeafJawPositions) returns wrong value 

### ISSUE THREAD

**Issue by JuergenDick** [fo-dicom/fo-dicom#567] opened 2017-07-21 09:29 UTC
### Expected behavior

DicomDataset.Get(DicomTag.LeafJawPositions, string.Empty); 
should return a string in the form of e.g "50\\40" or "20\\10\\7\\8" (see specification 
DICOM PS3.6 2017b - Data Dictionary, 
(300A,011C)​ | Leaf/Jaw Positions​ | LeafJawPositions​ | DS​ | 2-2n)

### Actual behavior
DicomDataset.Get(DicomTag.LeafJawPositions, string.Empty); 
returns a string "50" or "20"

### Steps to reproduce the behavior
load RTPLAN file

### fo-dicom version and OS/platform
3.0.2

**Comment by anders9ustafsson** [comment] 2017-07-21 17:31
@JuergenDick Actually, *fo-dicom* behaves as intended, although not everyone would argue that it behaves intuitively :-) I will close this issue as a duplicate, but there will be improvements related to your concern. Please see #491 for more details.

**Closed** 2017-07-21 17:33 UTC
Labels: duplicate

**Comment by JuergenDick** [comment] 2017-07-24 05:05
Ok, thanks!

**Comment by gofal** [comment] 2018-04-13 05:14
@JuergenDick, please review the new methods to access the dicom tags. They will be contained in the soon comming release. 
https://github.com/fo-dicom/fo-dicom/issues/491#issuecomment-380798639
