### ISSUE TITLE
[.NetCore]Encoding to JPEG2000Lossless is not handled correctly

### ISSUE THREAD

**Issue by pengchen0692** [fo-dicom/fo-dicom#1099] opened 2020-08-25 17:02 UTC
**Describe the bug**
When transcode from ExplicitVRLittleEndian to JPEG2000Lossless, the image is not converted correctly

**To Reproduce**
1. Convert given file to JPEG2000Lossless by  C# code :
```
string file = @"Input.dcm";
DicomFile dicomFile = DicomFile.Open(file);
DicomTranscoder transcoder = new DicomTranscoder(dicomFile.Dataset.InternalTransferSyntax, 
DicomTransferSyntax.JPEG2000Lossless);
transcoder.Transcode(dicomFile).Save("output.dcm");
```

- Expected:
The converted image should be same as original 

- Actual:
It looks like over exposed

 

**Screenshots or test DICOM files**

Original Image:
![image](https://user-images.githubusercontent.com/67345894/91204972-ac2a1a00-e6b9-11ea-9585-221030aa334f.png)
Converted Image:
![image](https://user-images.githubusercontent.com/67345894/91205006-b9470900-e6b9-11ea-9851-0962c64b321f.png)
Original dicomFile:
[Input.zip](https://github.com/fo-dicom/fo-dicom/files/5125251/Input.zip)
Converted DicomFile:
[Output.zip](https://github.com/fo-dicom/fo-dicom/files/5125254/Output.zip)

**Environment**
Fellow Oak DICOM version: ( 4.0.6)
OS: Windows 10 x64
Platform: .NetCore 3.1

**Comment by kira-96** [comment] 2020-08-26 07:25
> if you are building netcore and running on linux, then you can also take a look at https://github.com/Efferent-Health/Dicom-native. They shared their codec that runs on every netcore platform.

Refer to [Native codecs on .NET](https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET)

``` csharp
TranscoderManager.SetImplementation(Efferent.Native.Codec.NativeTranscoderManager.Instance);

string file = @"Input.dcm";
DicomFile dicomFile = DicomFile.Open(file);
DicomTranscoder transcoder = new DicomTranscoder(dicomFile.Dataset.InternalTransferSyntax,
DicomTransferSyntax.JPEG2000Lossless);
transcoder.Transcode(dicomFile).Save("output.dcm");
```

It works well.

**Comment by amoerie** [comment] 2020-08-26 07:53
I agree that for .NET core the recommended transcoder is the codecs by Efferent, but if we provide a managed decoder it should work. @gofal provided this decoder, so he's probably in the best position to investigate this problem.

Do note that the efferent transcoders do not seem to support multithreading on the same image, but that's still under investigation.

**Comment by pengchen0692** [comment] 2020-08-26 16:42
Thanks @kira-96  @amoerie :)
 I think Efferent is a very good alternative which has better performance and scope, one problem I encounter into is latest Efferent bound to fo-dicom 5.0 which is still prerelease version -- it's not convincing to use a prerelease version in production environment.

**Comment by amoerie** [comment] 2020-08-26 17:19
No the latest stable release of the efferent codecs should be fine, they've been around for a while. You shouldn't need any pre-release versions, neither from fo-dicom or efferent.

It's just that starting from fo-dicom 5.x, the efferent codecs will be the officially endorsed codecs and we will phase out the old codecs that are embedded in fo-dicom. That's why the efferent codecs are changing names, so that it's obvious they are the "official ones" going from 5.x forward.

**Comment by pengchen0692** [comment] 2020-08-26 17:29
@amoerie Perfect, I'm not aware they have a different name before!
![image](https://user-images.githubusercontent.com/67345894/91336548-ec0b0300-e786-11ea-9368-199b481325ad.png)

**Comment by amoerie** [comment] 2020-08-27 09:53
@gofal quick summary so far: there seems to be an issue in the managed decoder of JPEG Lossless, sample DICOM file can be found at the top. There is an easy workaround: use the latest stable efferent codecs. But perhaps we should also fix this issue in the managed decoder, no?

**Comment by gofal** [comment] 2020-08-30 20:25
@amoerie where is this managed JpegLossless decoder invoked? The issue is about encoding from uncompressed to J2kLosless. Then the output is rendered wrong, wo fo-dicom uses the j2kLossless decoder to render. JpegLossless is not involved in this all?

**Comment by amoerie** [comment] 2020-08-30 20:53
> @amoerie where is this managed JpegLossless decoder invoked? The issue is about encoding from uncompressed to J2kLosless. Then the output is rendered wrong, wo fo-dicom uses the j2kLossless decoder to render. JpegLossless is not involved in this all?
> 

I was mixing J2K with JPEG lossless, please disregard what I said 😭

**Comment by gofal** [comment] 2020-08-31 09:34
related to #1083?

**Comment by gofal** [comment] 2020-10-05 15:52
It will be hard to fix this in Jpeg2k codec. If there is anyone who knows how to fix it, then you are welcome.
Since the codec from Efferent is working, I will close this issue as "wontfix".

Please reopen this if you think there is still something left open to do.

**Closed by gofal** 2020-10-05 15:52 UTC
Labels: wontfix
