### ISSUE TITLE
PixelData.AddFrame does not pad to even length for encapsulated transfer syntax.

### ISSUE THREAD

**Issue by yvdh** [fo-dicom/fo-dicom#1012] opened 2020-04-08 13:07 UTC
### Expected behavior
Buffer is padded to even length.

### Actual behavior
No padding is added for encapsulated transfer syntax.

### Steps to reproduce the behavior
1. Take an mp4 AVC video of uneven length (or a pdf)
2. Put into pixeldata with encapsulated transfer syntax.
3. Check with dciodvfy: warning about uneven length pixeldata.
4. Upload to Agfa EI: IOException
5. Save as local dicom file, some DicomViewers work with these and open a system viewer for the encapsulated data.

###Workaround
Use the next method to pad buffer from an encoded file!

    ```
/// <summary>
    /// Get the raw (undecoded) data, straight from the file.
    /// </summary>
    /// <param name="filename"></param>
    /// <param name="padEven">Whether or not tor padd the buffer so that the length is even. 
    /// This is needed for pixel data in any encapsulated transfer syntax.</param>
    /// <returns></returns>
    /// <remarks>This is unbuffered so it will fail for large files ...</remarks>
    private static byte[] GetFileData(string filename, bool padEven)
    {
      byte[] buffer;
      FileStream fileStream = new FileStream(filename, FileMode.Open, FileAccess.Read);
      try
      {
        int length = (int)fileStream.Length;  // get file length
        int bufferLength = padEven ? (length + length % 2):length;

        buffer = new byte[bufferLength];      // create buffer
        int count;                            // actual number of bytes read
        int sum = 0;                          // total number of bytes read

        // read until Read method returns 0 (end of the stream has been reached)
        while ((count = fileStream.Read(buffer, sum, length - sum)) > 0)
          sum += count;  // sum is a buffer offset for next reading
      }
      finally
      {
        fileStream.Close();
      }
      return buffer;
    }
```

### fo-dicom version and OS/platform
4.0.4
Windows 10 64
Visual Studio 2017, C#

**Comment by aerik** [comment] 2020-04-20 17:29
I am wrestling with the opposite issue.  IMHO, each frame does not neet to be padded, only the resultant element value (I am dealing with multi-frame images).

Can you post sample code for your bug's behaviour?

**Comment by gofal** [comment] 2020-05-02 18:54
Agree that the OW tag must have even length. And I also think that DICOM means that the whole Tag must have even length, not every single fragment.
fo-dicom currently does not change the pure byte stream when creating it "manually". it was assumed that when you create the bytes yourself that you know about making it even.
The transcoders within fo-dicom, that create the data out of existing pixel data, should behave fine and create even length. Or did you observe a bug there too?

for a very long time fo-dicom did only very few checks. I introduces validation/check of the VR-definitions (length of dicom tags, allowed characters, ..) in version 4.0.2. Surprisingly in the first version this caused quite some issues.

This would be the next step to take responsibility from the developer into fo-dicom and I want to be very careful there:
Could there be any disadvantage?

**Comment by gofal** [comment] 2022-11-22 18:13
would this PR #1410 be a fix for this issue?

**Comment by gofal** [comment] 2024-03-25 08:40
Please verify, that PR #1474  fixed this issue.
If the issue is still with the latest version of fo-dicom, then please feel free to reopen this issue and provide actual informations.

**Closed by gofal** 2024-03-25 08:40 UTC
Labels: evaluating
