### ISSUE TITLE
Full control of DicomAssociation

### ISSUE THREAD

**Issue by raise** [fo-dicom/fo-dicom#507] opened 2017-03-29 15:48 UTC
### Expected behavior
Open and close association as needed

### Actual behavior
Automatically controlled by DicomClient

### Steps to reproduce the behavior
There is no such method

### fo-dicom version and OS/platform
fo-dicom 3.0.1 via nuget

**Comment by anders9ustafsson** [comment] 2017-03-29 16:04
Duplicate of #508.

**Closed by anders9ustafsson** 2017-03-29 16:04 UTC
Labels: duplicate
