### ISSUE TITLE
4.0.4 DicomClient stucks on SendAsync() for hours

### ISSUE THREAD

**Issue by oo-dev17** [fo-dicom/fo-dicom#1054] opened 2020-06-23 10:12 UTC
Dear contributors and supporters, I have the following problem. Thank you in advance for reading!

### Expected behavior
SendAsync() should return (or crash) at least within timeout (set to 2 minutes)

### Actual behavior
About once in a few weeks it happens that SendAsync() never returns - for hours.
The rest of my appl is running and collecting images.

### Steps to reproduce the behavior
quite difficult, very seldom

### fo-dicom version and OS/platform
4.0.4* in .NET 4.8 x86 exe on Windows Server 

*unfortunately I am currently not able to update to 4.0.5 here - If an update to 4.0.5 might solve this, it would be a very interesting information

I am calling the send like:
`try{
// preparation here
await dicomClient.SendAsync();
} catch (exception e)
{
Log("This is not seen when problm happens");
}`
(I am very sorry if I am wrong - or use the library wrong....)

The log shortly before it stucks is:
...
```
12:16:02,833 Trace - DicomLog(): VI-DEMO1 -> C-Store request [22450]
12:16:02,989 Trace - DicomLog(): VI-DEMO1 <- C-Store response [22450]: Success
12:16:02,989 Trace - DicomLog(): [SENDING REQUESTS] All requests are done, going to linger association now...
12:16:02,989 Trace - DicomLog(): [SENDING REQUESTS] --> [LINGERING ASSOCIATION]
12:16:03,052 Trace - DicomLog(): [LINGERING ASSOCIATION] Linger timed out after 50ms, releasing association
12:16:03,052 Trace - DicomLog(): [LINGERING ASSOCIATION] --> [RELEASING ASSOCIATION]
12:16:03,052 Trace - DicomLog(): VI-DEMO1 -> Association release request
12:16:03,052 Trace - DicomLog(): VI-DEMO1 <- Association release response
12:16:03,052 Trace - DicomLog(): Connection closed
12:16:03,052 Trace - DicomLog(): [RELEASING ASSOCIATION] Association release response received, disconnecting...
12:16:03,052 Trace - DicomLog(): [RELEASING ASSOCIATION] --> [COMPLETED]
12:16:03,052 Trace - DicomLog(): [COMPLETED] DICOM client completed without errors
12:16:03,052 Trace - DicomLog(): [COMPLETED] Cleaning up
12:16:03,052 Trace - DicomLog(): [COMPLETED] --> [IDLE]
12:16:03,052 Trace - DicomLog(): [IDLE] No requests to send, staying idle
12:16:03,271 Trace - DicomLog(): [IDLE] --> [CONNECTING]
12:16:03,271 Trace - DicomLog(): [CONNECTING] --> [REQUESTING ASSOCIATION]
12:16:03,271 Trace - DicomLog(): VI-DEMO1 -> Association request:
12:16:03,271 Trace - DicomLog(): VI-DEMO1 <- Association accept:
12:16:03,271 Trace - DicomLog(): [REQUESTING ASSOCIATION] Association is accepted
12:16:03,271 Trace - DicomLog(): [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
12:16:03,271 Trace - DicomLog(): [SENDING REQUESTS] Sending DICOM requests
12:16:03,271 Trace - DicomLog(): VI-DEMO1 -> C-Store request [22451]
12:16:03,411 Trace - DicomLog(): [SENDING REQUESTS] DICOM client connection still has unsent requests, sending those now...
12:16:03,427 Trace - DicomLog(): VI-DEMO1 <- C-Store response [22451]: Success
12:16:03,443 Trace - DicomLog(): VI-DEMO1 -> C-Store request [22452]
12:16:03,583 Trace - DicomLog(): VI-DEMO1 <- C-Store response [22452]: Success
12:16:03,583 Trace - DicomLog(): VI-DEMO1 -> C-Store request [22453]
12:16:03,724 Trace - DicomLog(): VI-DEMO1 <- C-Store response [22453]: Success
12:16:03,724 Trace - DicomLog(): [SENDING REQUESTS] All requests are done, going to linger association now...
12:16:03,724 Trace - DicomLog(): [SENDING REQUESTS] --> [LINGERING ASSOCIATION]
12:16:03,786 Trace - DicomLog(): [LINGERING ASSOCIATION] Linger timed out after 50ms, releasing association
12:16:03,786 Trace - DicomLog(): [LINGERING ASSOCIATION] --> [RELEASING ASSOCIATION]
12:16:03,786 Trace - DicomLog(): VI-DEMO1 -> Association release request
12:16:03,786 Trace - DicomLog(): VI-DEMO1 <- Association release response
12:16:03,786 Trace - DicomLog(): Connection closed
12:16:03,786 Trace - DicomLog(): [RELEASING ASSOCIATION] Disconnected during association release, cleaning up...
12:16:03,786 Trace - DicomLog(): [RELEASING ASSOCIATION] --> [COMPLETED]
12:16:03,786 Trace - DicomLog(): [COMPLETED] DICOM client completed without errors
12:16:03,786 Trace - DicomLog(): [COMPLETED] Cleaning up
12:16:03,786 Trace - DicomLog(): [COMPLETED] --> [IDLE]
12:16:03,786 Trace - DicomLog(): [IDLE] No requests to send, staying idle
12:16:04,005 Trace - DicomLog(): [IDLE] --> [CONNECTING]
12:16:04,005 Trace - DicomLog(): [CONNECTING] --> [REQUESTING ASSOCIATION]
12:16:04,005 Trace - DicomLog(): VI-DEMO1 -> Association request:
12:16:04,005 Trace - DicomLog(): VI-DEMO1 <- Association accept:
12:16:04,005 Trace - DicomLog(): [REQUESTING ASSOCIATION] Association is accepted
12:16:04,005 Trace - DicomLog(): [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
12:16:04,005 Trace - DicomLog(): [SENDING REQUESTS] Sending DICOM requests
12:16:04,021 Trace - DicomLog(): VI-DEMO1 -> C-Store request [22460]
12:16:23,130 Trace - DicomLog(): Socket error while reading PDU: TimedOut [10060]
12:16:23,130 Trace - DicomLog(): Socket error while writing PDU: ConnectionReset [10054]
12:16:23,130 Trace - DicomLog(): Connection closed
12:16:23,130 Trace - DicomLog(): Connection closed
12:16:24,068 Warn - DicomLog(): Exception creating PDV: System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
12:16:24,099 Warn - DicomLog(): Exception writing data to PDV: System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
12:16:24,162 Warn - DicomLog(): Exception sending DIMSE: System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
12:16:24,162 Trace - DicomLog(): VI-DEMO1 -> C-Store request [22461]
```

**Comment by gofal** [comment] 2020-06-25 19:07
@amoerie is the expert in this field. I hope he will find time to take a closer look at this, otherwise I will dive into it soon.

**Comment by amoerie** [comment] 2020-06-25 19:57
Thanks for tagging me @gofal , I'll try and take a look tomorrow. I have a few thoughts on what could be going on.

The DicomClientSendingRequestsState has a few edge cases where it might freeze, for example when considerable errors happen during sending, maybe it doesn't reset the _sending flag.

I am also aware of a potential issue in the DicomService where things can go wrong when a Socket exception occurs.

Until I know more, if anyone could provide a failing test, that would be of tremendous value. I am also interested in the exact options you have configured on your DicomClient, if they deviate from the default values @oo-dev17

**Comment by amoerie** [comment] 2020-06-25 19:59
P.S. for now, please pass along a CancellationToken to the SendAsync method. If you can detect a freeze yourself, canceling the token should bring the DicomClient back to its senses. Any requests in transit would, unfortunately, be lost.

**Comment by oo-dev17** [comment] 2020-06-26 06:57
@amoerie my options and set up of the dicomClient
```
dicomClient = new Dicom.Network.Client.DicomClient(ReceiverIP, ReceiverPort, false, SenderAeTitle, ReceiverAeTitle);
dicomClient.Options = new Dicom.Network.DicomServiceOptions() { LogDataPDUs = false, LogDimseDatasets = false };
dicomClient.Options.RequestTimeout = new TimeSpan(0, 2, 0);
dicomClient.Logger = new MyDicomLogger();
dicomClient.NegotiateAsyncOps(1, 1); 
```

I have event handlers connected to _AssociationReleased, AssociationRejected, AssociationAccepted, RequestTimedOut_
Then I create  requests with also event handlers on _OnResponseReceived_ and _OnTimeout_ -  and add them like `await dicomClient.AddRequestAsync(request);   `
and then I call `await dicomClient.SendAsync()  ` inside a try/catch

This all in one (async) method - where the origin of this task is a System.Timers.Timer.Elapsed event ... that was my best idea to have this 'thread' separate - and not calling it from maybe other blocking threads.

Thank you a lot (also for the workaround!) and best regards

**Comment by amoerie** [comment] 2020-06-29 08:12
As you might have noticed, I started a PR that (possibly) addresses the problem you are having.

Unfortunately, I can only say it "possibly" fixes your problem, as I have not been able to consistently reproduce the issue in a test. 

I'll keep you posted on further progress, please bear with me. In the meantime, I hope the cancellationtoken workaround is sufficient to stabilize your project.

**Comment by gofal** [comment] 2020-07-09 11:11
honestly I do not know the reason any more.
The old Dicomclient hat some issues and there have been quite a lot of fixes added here and there. Many "in that case we should to this, so add a flag variable...". You then completely reworked the DicomClient. So I am sure many of these flags are not required any more.
The only question I ask myself: if you remove them, then it should work fine with the new DicomClient, but will it make the old DicomClient more unstable again? Should this change be done only in version 5?

**Comment by amoerie** [comment] 2020-07-09 11:15
To be honest, I think this issue affects both the old DicomClient and the new DicomClient equally. The issue is in DicomService, in the sending of a PDU over the network stream. Similar to the old DicomClient, the new DicomClient has little control over what happens when it calls "SendNextMessageAsync" to the DicomService. The only way the old DicomClient would be able to avoid this issue is if it had any logic that detects a never ending loop, but I don't think it had anything for this scenario.

In my opinion, we should do the fix for both version 4 and version 5. 

A lot of the flags that you mentioned lived mostly in the old DicomClient and in DicomServiceUser, which are now obsolete and can be cleaned up (definitely for version 5). I'm not aware of any flags in DicomService that exist solely for the purpose of pleasing the DicomClient.

**Comment by amoerie** [comment] 2020-07-09 12:13
I think I have successfully created a test that reproduces the problem. See https://ci.appveyor.com/project/anders9ustafsson/fo-dicom/builds/33999874/tests 

The test uses a decorated NetworkStream that starts throwing exceptions for each attempt to write to ths stream after the first request has been processed. The exception deliberately does not inherit from IOException, to demonstrate the problem that the DicomService infinitely keeps retrying the sending of a PDU.  (because the DicomRequest is never cleared from its queue)

Now I would be interested to hear your thoughts on how to solve this matter.
I've looked at the infinite loop that processes incoming messages from the network stream (method ListenAndProcessPDU) and this actually force closes the connection in the generic "Exception" catch block. 

It is still not clear to me why we cannot do the same when writing to the network stream.

**Comment by amoerie** [comment] 2020-07-09 13:13
Update: 

- I've enabled force closing of the connection when something goes wrong while writing a PDU over the network stream. This seems to break zero other tests, and makes my new test green. 
- I've applied the same changes to the 5.0 line, and added the same new tests there (slightly modified to adhere to the new syntax for creating clients and so on, of course)

**Comment by amoerie** [comment] 2020-07-09 15:11
Update:

- The 5.0 line build and tests are now green in Github Actions for every target framework (.NET Framework 4.6.2, .NET Core 2.1 and .NET Core 3.1). I've updated the YAML file so that each target framework runs in parallel. 
- The 4.0 line build and tests have been green for a while already in AppVeyor, but there's a bit of a backlog

I've flagged the PR for review by @gofal because there are a few tricky changes.

**Comment by amoerie** [comment] 2020-07-10 21:50
Another update: I think the core issue has been fixed, but my GitHub workflow changes seem to have unintended consequences for the tests. If I can't find a good solution, I'll revert the changes to the GitHub Actions config.

**Comment by amoerie** [comment] 2020-07-13 09:17
More updates: I've found the root cause of the Github CI issues, the problem is unrelated to the changes I've made here, but my gitlab CI config changes made it more visible. I have found a solution, and am now confirming that the tests stay consistently green.

**Closed** 2020-08-03 12:03 UTC
Labels: bug

**Comment by marcoafo** [comment] 2022-03-23 17:15
Just a side note, I've come accross a bug server that would make DicomClient halt forever. Testing the comm with DCMTK would give:

D: Parsing an A-ASSOCIATE PDU
T: PDU type: 2 (A-ASSOCIATE AC), PDU Length: 207
T: DICOM Protocol: 1
T: Called AP Title:  ANY-SCP
T: Calling AP Title: STORESCU
T: Parsing remaining 139 bytes of A-ASSOCIATE PDU
T: Next item type: 10
T: Subitem parse: Type 10, Length 0021, Content: 1.2.840.10008.3.1.1.1
T: Successfully parsed Application Context
T: Parsing remaining 114 bytes of A-ASSOCIATE PDU
T: Next item type: 21
T: Parsing Presentation Context: (21), Length: 25
T: Presentation Context ID: fd
T: Parsing remaining 21 bytes of Presentation Context
T: Next item type: 40
F: Association Request Failed: 0006:0307 DUL Illegal or ill-formed PDU
F: 0006:0308 DUL Illegal subitem. Got 21 bytes of data with a length field of 19 (data before length field is not included in length field).

Of course the connection drops, but at least it moved on. Regardless of the problem itself, the pull #1332 seems to fix that. It didn't give a full error description, but still it wouldn't hang the code forever. So, for me, vote up for that.

**Comment by iberisoft** [comment] 2025-02-25 19:44
I should confirm a similar strange behavior in v4.

This code is working for hours by continuously displaying errors if the server host is down:
```
        var client = new DicomClient(job.Destination.Host, job.Destination.Port, false, job.Destination.RouterAeTitle, job.Destination.AeTitle);
        client.NegotiateAsyncOps();
        var request = new DicomCStoreRequest(file);
        await client.AddRequestAsync(request);
        await client.SendAsync();
```

The log repeats the following fragment thousands of times w/o returning any exception:
```
[20:35:12 INF] SERVER -> Association request:
Calling AE Title:          ROUTER
Called AE Title:           SERVER
Remote host:               0.tcp.eu.ngrok.io
Remote port:               66666
Implementation Class:      Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version:    fo-dicom 4.0.8
Maximum PDU Length:        0
Async Ops Invoked:         0
Async Ops Performed:       0
Presentation Contexts:     2
  Presentation Context:     1 [Proposed]
       Abstract Syntax:     Computed Radiography Image Storage
       Transfer Syntax:     Explicit VR Little Endian
  Presentation Context:     3 [Proposed]
       Abstract Syntax:     Computed Radiography Image Storage
       Transfer Syntax:     Implicit VR Little Endian: Default Transfer Syntax for DICOM
[20:35:12 INF] Connection closed
[20:35:12 WRN] [REQUESTING ASSOCIATION] Disconnected
```

I have never seen this strange behavior...

**Summary**
I remember some other issues in `DicomClient`. All this motivates me to migrate to v5!
