### ISSUE TITLE
QueryRetrieve SCU (WPF desktop app): no deterministic behaviour

### ISSUE THREAD

**Issue by WernMich** [fo-dicom/fo-dicom#644] opened 2017-12-04 10:17 UTC
### Expected behavior
QueryRetrieve SCU should work deterministic. 

### Actual behavior
In my prototype WPF app, I sometimes getting socket read timeouts on SCP which is a dcm4chee instance (on local host). 

### Steps to reproduce the behavior
QueryRetrieve SCU sample as WPF desktop app with corrected move sample (local SCP is running fine). Continuosly running the QueryRetrieve procedure. In at least 50% socket read timeouts at SCP side and no datasets become received from SCU.

Workaround: implemented a Thread.Sleep(100); after every client.Send(...) call -> works then deterministic in my setup.

### fo-dicom version and OS/platform
Win 10 Pro 64-Bit, fo-dicom (nuget package) v3.0.2.0. Target framework version of WPF app: v4.5.2

**Comment by FKupsch** [comment] 2017-12-11 09:28
Hi Michael,

there is no need for calling  client.Release() after client.Send(...). Calling client.Send(...) will try to open an association, send the added requests, receive responses and close it, when finished. Calling Release() is probably the cause of your troubles.

Felix

**Comment by WernMich** [comment] 2017-12-11 09:58
Hi again,

the WPF app only works if Release() is called manually! It does NOT work if Release() is not called (or a Thread.Sleep(..) is not called instead.

Michael

**Comment by WernMich** [comment] 2017-12-11 11:10
Hi,

I could perform some deeper investigation: in method "private async Task<bool> ListenForDisconnectAsync(int millisecondsDelay, bool releaseRequested)" in DicomClient class I am running continously into the catch of the TaskCanceledException handler. I do not get the meaning of the "await Task.Delay(1, cancellationSource.Token).ConfigureAwait(false);" statement.
 
Michael

**Comment by WernMich** [comment] 2017-12-11 12:03
Ok I got the meaning, it should cancel the task (which is mostly the while-loop) when linger time is elapsed. So in my case, the disconnect does not occur within that period and it runs into the cancel exception handler. I do not get now why there should occur a disconnect. But without a diconnect the while loop will run until the exception occurs (linger time elapsed). Simply increasing the linger time does not work because the disconnect never happens.

**Comment by FKupsch** [comment] 2017-12-11 17:24
Do you call client.NegotiateAsyncOps(); lie its done in the sample? If yes, then outcomment it and try again. Explicitely releasing the association should not be necessary. That's the reason behind LingerAsync.

**Comment by WernMich** [comment] 2017-12-11 18:07
It tried it with and without calling NegotiateAsyncOps() - it doesn't work in both cases :(

**Comment by WernMich** [comment] 2017-12-12 08:31
[DicomClientPrototype.zip](https://github.com/fo-dicom/fo-dicom/files/1550749/DicomClientPrototype.zip)
Uploaded my prototype test app, maybe someone can test it. IMPORTANT: do not debug (breakpoints) the app, because then it runs in most cases without problems as already described. If it is run without interruption, then you should notice that the C-FIND responses of the second C-FIND will not be correct (missing studies or missing series).

**Comment by FKupsch** [comment] 2017-12-12 11:33
I tested it with DVT and it seems to work as intendend. Maybe the problem is caused by your SCP. Can you provide a log file?

**Comment by WernMich** [comment] 2017-12-12 12:31
Here is a "clean" log from SCP (DCM4CHEE 2.18.3)
[server.log](https://github.com/fo-dicom/fo-dicom/files/1551545/server.log)

**Comment by FKupsch** [comment] 2017-12-12 13:57
The logs are showing nothing unusual (2 associations with one c-find-rq). You must not add the additional presentation contexts, because the toolkit adds what it needs to send the request and you will end up with duplicate presentation context in your association request. But this is probably not the reason for your problem. 

Sorry I can not reproduce it and I do not really understand what's going wrong. It works fine with different tools on my site.

**Comment by WernMich** [comment] 2017-12-12 14:05
Ok, thanks for your time & investigation! I supposed that this is a special behaviour on my machine :( Where do you run your SCP? Locally on the same machine as SCU or is it a remote machine? My SCP is running on a Virtual Box VM (WinXP) - maybe this can cause troubles in network communication.

**Closed** 2018-03-23 10:48 UTC
